apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: gix-coder
  labels:
    app: gateway
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: grpc
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: metrics
  selector:
    app: gateway
