// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: api/proto/gix/router/v1/router.proto

package routerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RouterService_ClassifyTask_FullMethodName   = "/gix.router.v1.RouterService/ClassifyTask"
	RouterService_SelectModel_FullMethodName    = "/gix.router.v1.RouterService/SelectModel"
	RouterService_ValidateOutput_FullMethodName = "/gix.router.v1.RouterService/ValidateOutput"
	RouterService_CheckBudget_FullMethodName    = "/gix.router.v1.RouterService/CheckBudget"
	RouterService_ReleaseBudget_FullMethodName  = "/gix.router.v1.RouterService/ReleaseBudget"
	RouterService_GetProviders_FullMethodName   = "/gix.router.v1.RouterService/GetProviders"
	RouterService_HealthLive_FullMethodName     = "/gix.router.v1.RouterService/HealthLive"
	RouterService_HealthReady_FullMethodName    = "/gix.router.v1.RouterService/HealthReady"
)

// RouterServiceClient is the client API for RouterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouterServiceClient interface {
	ClassifyTask(ctx context.Context, in *ClassifyTaskRequest, opts ...grpc.CallOption) (*ClassifyTaskResponse, error)
	SelectModel(ctx context.Context, in *SelectModelRequest, opts ...grpc.CallOption) (*SelectModelResponse, error)
	ValidateOutput(ctx context.Context, in *ValidateOutputRequest, opts ...grpc.CallOption) (*ValidateOutputResponse, error)
	CheckBudget(ctx context.Context, in *CheckBudgetRequest, opts ...grpc.CallOption) (*CheckBudgetResponse, error)
	ReleaseBudget(ctx context.Context, in *ReleaseBudgetRequest, opts ...grpc.CallOption) (*ReleaseBudgetResponse, error)
	GetProviders(ctx context.Context, in *GetProvidersRequest, opts ...grpc.CallOption) (*GetProvidersResponse, error)
	HealthLive(ctx context.Context, in *HealthLiveRequest, opts ...grpc.CallOption) (*HealthLiveResponse, error)
	HealthReady(ctx context.Context, in *HealthReadyRequest, opts ...grpc.CallOption) (*HealthReadyResponse, error)
}

type routerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterServiceClient(cc grpc.ClientConnInterface) RouterServiceClient {
	return &routerServiceClient{cc}
}

func (c *routerServiceClient) ClassifyTask(ctx context.Context, in *ClassifyTaskRequest, opts ...grpc.CallOption) (*ClassifyTaskResponse, error) {
	out := new(ClassifyTaskResponse)
	err := c.cc.Invoke(ctx, RouterService_ClassifyTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) SelectModel(ctx context.Context, in *SelectModelRequest, opts ...grpc.CallOption) (*SelectModelResponse, error) {
	out := new(SelectModelResponse)
	err := c.cc.Invoke(ctx, RouterService_SelectModel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ValidateOutput(ctx context.Context, in *ValidateOutputRequest, opts ...grpc.CallOption) (*ValidateOutputResponse, error) {
	out := new(ValidateOutputResponse)
	err := c.cc.Invoke(ctx, RouterService_ValidateOutput_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) CheckBudget(ctx context.Context, in *CheckBudgetRequest, opts ...grpc.CallOption) (*CheckBudgetResponse, error) {
	out := new(CheckBudgetResponse)
	err := c.cc.Invoke(ctx, RouterService_CheckBudget_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) ReleaseBudget(ctx context.Context, in *ReleaseBudgetRequest, opts ...grpc.CallOption) (*ReleaseBudgetResponse, error) {
	out := new(ReleaseBudgetResponse)
	err := c.cc.Invoke(ctx, RouterService_ReleaseBudget_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) GetProviders(ctx context.Context, in *GetProvidersRequest, opts ...grpc.CallOption) (*GetProvidersResponse, error) {
	out := new(GetProvidersResponse)
	err := c.cc.Invoke(ctx, RouterService_GetProviders_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) HealthLive(ctx context.Context, in *HealthLiveRequest, opts ...grpc.CallOption) (*HealthLiveResponse, error) {
	out := new(HealthLiveResponse)
	err := c.cc.Invoke(ctx, RouterService_HealthLive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerServiceClient) HealthReady(ctx context.Context, in *HealthReadyRequest, opts ...grpc.CallOption) (*HealthReadyResponse, error) {
	out := new(HealthReadyResponse)
	err := c.cc.Invoke(ctx, RouterService_HealthReady_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServiceServer is the server API for RouterService service.
// All implementations must embed UnimplementedRouterServiceServer
// for forward compatibility
type RouterServiceServer interface {
	ClassifyTask(context.Context, *ClassifyTaskRequest) (*ClassifyTaskResponse, error)
	SelectModel(context.Context, *SelectModelRequest) (*SelectModelResponse, error)
	ValidateOutput(context.Context, *ValidateOutputRequest) (*ValidateOutputResponse, error)
	CheckBudget(context.Context, *CheckBudgetRequest) (*CheckBudgetResponse, error)
	ReleaseBudget(context.Context, *ReleaseBudgetRequest) (*ReleaseBudgetResponse, error)
	GetProviders(context.Context, *GetProvidersRequest) (*GetProvidersResponse, error)
	HealthLive(context.Context, *HealthLiveRequest) (*HealthLiveResponse, error)
	HealthReady(context.Context, *HealthReadyRequest) (*HealthReadyResponse, error)
	mustEmbedUnimplementedRouterServiceServer()
}

// UnimplementedRouterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRouterServiceServer struct {
}

func (UnimplementedRouterServiceServer) ClassifyTask(context.Context, *ClassifyTaskRequest) (*ClassifyTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassifyTask not implemented")
}
func (UnimplementedRouterServiceServer) SelectModel(context.Context, *SelectModelRequest) (*SelectModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectModel not implemented")
}
func (UnimplementedRouterServiceServer) ValidateOutput(context.Context, *ValidateOutputRequest) (*ValidateOutputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateOutput not implemented")
}
func (UnimplementedRouterServiceServer) CheckBudget(context.Context, *CheckBudgetRequest) (*CheckBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckBudget not implemented")
}
func (UnimplementedRouterServiceServer) ReleaseBudget(context.Context, *ReleaseBudgetRequest) (*ReleaseBudgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseBudget not implemented")
}
func (UnimplementedRouterServiceServer) GetProviders(context.Context, *GetProvidersRequest) (*GetProvidersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviders not implemented")
}
func (UnimplementedRouterServiceServer) HealthLive(context.Context, *HealthLiveRequest) (*HealthLiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthLive not implemented")
}
func (UnimplementedRouterServiceServer) HealthReady(context.Context, *HealthReadyRequest) (*HealthReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthReady not implemented")
}
func (UnimplementedRouterServiceServer) mustEmbedUnimplementedRouterServiceServer() {}

// UnsafeRouterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouterServiceServer will
// result in compilation errors.
type UnsafeRouterServiceServer interface {
	mustEmbedUnimplementedRouterServiceServer()
}

func RegisterRouterServiceServer(s grpc.ServiceRegistrar, srv RouterServiceServer) {
	s.RegisterService(&RouterService_ServiceDesc, srv)
}

func _RouterService_ClassifyTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ClassifyTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_ClassifyTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ClassifyTask(ctx, req.(*ClassifyTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_SelectModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).SelectModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_SelectModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).SelectModel(ctx, req.(*SelectModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ValidateOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ValidateOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_ValidateOutput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ValidateOutput(ctx, req.(*ValidateOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_CheckBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).CheckBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_CheckBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).CheckBudget(ctx, req.(*CheckBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_ReleaseBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).ReleaseBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_ReleaseBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).ReleaseBudget(ctx, req.(*ReleaseBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_GetProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).GetProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_GetProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).GetProviders(ctx, req.(*GetProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_HealthLive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthLiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).HealthLive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_HealthLive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).HealthLive(ctx, req.(*HealthLiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterService_HealthReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServiceServer).HealthReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterService_HealthReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServiceServer).HealthReady(ctx, req.(*HealthReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RouterService_ServiceDesc is the grpc.ServiceDesc for RouterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gix.router.v1.RouterService",
	HandlerType: (*RouterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClassifyTask",
			Handler:    _RouterService_ClassifyTask_Handler,
		},
		{
			MethodName: "SelectModel",
			Handler:    _RouterService_SelectModel_Handler,
		},
		{
			MethodName: "ValidateOutput",
			Handler:    _RouterService_ValidateOutput_Handler,
		},
		{
			MethodName: "CheckBudget",
			Handler:    _RouterService_CheckBudget_Handler,
		},
		{
			MethodName: "ReleaseBudget",
			Handler:    _RouterService_ReleaseBudget_Handler,
		},
		{
			MethodName: "GetProviders",
			Handler:    _RouterService_GetProviders_Handler,
		},
		{
			MethodName: "HealthLive",
			Handler:    _RouterService_HealthLive_Handler,
		},
		{
			MethodName: "HealthReady",
			Handler:    _RouterService_HealthReady_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/gix/router/v1/router.proto",
}
