// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/proto/gix/router/v1/router.proto

package routerv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ClassifyTaskRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ClassifyTaskRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClassifyTaskRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ClassifyTaskRequestMultiError, or nil if none found.
func (m *ClassifyTaskRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ClassifyTaskRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Prompt

	// no validation rules for Context

	// no validation rules for WorkflowType

	// no validation rules for TenantId

	// no validation rules for CorrelationId

	if len(errors) > 0 {
		return ClassifyTaskRequestMultiError(errors)
	}

	return nil
}

// ClassifyTaskRequestMultiError is an error wrapping multiple validation
// errors returned by ClassifyTaskRequest.ValidateAll() if the designated
// constraints aren't met.
type ClassifyTaskRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClassifyTaskRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClassifyTaskRequestMultiError) AllErrors() []error { return m }

// ClassifyTaskRequestValidationError is the validation error returned by
// ClassifyTaskRequest.Validate if the designated constraints aren't met.
type ClassifyTaskRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClassifyTaskRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClassifyTaskRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClassifyTaskRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClassifyTaskRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClassifyTaskRequestValidationError) ErrorName() string {
	return "ClassifyTaskRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ClassifyTaskRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClassifyTaskRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClassifyTaskRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClassifyTaskRequestValidationError{}

// Validate checks the field values on ClassifyTaskResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ClassifyTaskResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClassifyTaskResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ClassifyTaskResponseMultiError, or nil if none found.
func (m *ClassifyTaskResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ClassifyTaskResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Complexity

	// no validation rules for Domain

	// no validation rules for EstimatedTokens

	// no validation rules for LatencyRequirementMs

	if len(errors) > 0 {
		return ClassifyTaskResponseMultiError(errors)
	}

	return nil
}

// ClassifyTaskResponseMultiError is an error wrapping multiple validation
// errors returned by ClassifyTaskResponse.ValidateAll() if the designated
// constraints aren't met.
type ClassifyTaskResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClassifyTaskResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClassifyTaskResponseMultiError) AllErrors() []error { return m }

// ClassifyTaskResponseValidationError is the validation error returned by
// ClassifyTaskResponse.Validate if the designated constraints aren't met.
type ClassifyTaskResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClassifyTaskResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClassifyTaskResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClassifyTaskResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClassifyTaskResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClassifyTaskResponseValidationError) ErrorName() string {
	return "ClassifyTaskResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ClassifyTaskResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClassifyTaskResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClassifyTaskResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClassifyTaskResponseValidationError{}

// Validate checks the field values on SelectModelRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SelectModelRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SelectModelRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SelectModelRequestMultiError, or nil if none found.
func (m *SelectModelRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SelectModelRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetClassification()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SelectModelRequestValidationError{
					field:  "Classification",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SelectModelRequestValidationError{
					field:  "Classification",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetClassification()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SelectModelRequestValidationError{
				field:  "Classification",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for TenantId

	// no validation rules for WorkflowId

	// no validation rules for TokenBudget

	for idx, item := range m.GetAllowedModels() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SelectModelRequestValidationError{
						field:  fmt.Sprintf("AllowedModels[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SelectModelRequestValidationError{
						field:  fmt.Sprintf("AllowedModels[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SelectModelRequestValidationError{
					field:  fmt.Sprintf("AllowedModels[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for PolicyVersion

	if len(errors) > 0 {
		return SelectModelRequestMultiError(errors)
	}

	return nil
}

// SelectModelRequestMultiError is an error wrapping multiple validation errors
// returned by SelectModelRequest.ValidateAll() if the designated constraints
// aren't met.
type SelectModelRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SelectModelRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SelectModelRequestMultiError) AllErrors() []error { return m }

// SelectModelRequestValidationError is the validation error returned by
// SelectModelRequest.Validate if the designated constraints aren't met.
type SelectModelRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SelectModelRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SelectModelRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SelectModelRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SelectModelRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SelectModelRequestValidationError) ErrorName() string {
	return "SelectModelRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SelectModelRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSelectModelRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SelectModelRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SelectModelRequestValidationError{}

// Validate checks the field values on SelectModelResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SelectModelResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SelectModelResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SelectModelResponseMultiError, or nil if none found.
func (m *SelectModelResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SelectModelResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ModelId

	// no validation rules for Provider

	// no validation rules for Endpoint

	// no validation rules for TokenBudget

	// no validation rules for Parameters

	// no validation rules for EstimatedCost

	if len(errors) > 0 {
		return SelectModelResponseMultiError(errors)
	}

	return nil
}

// SelectModelResponseMultiError is an error wrapping multiple validation
// errors returned by SelectModelResponse.ValidateAll() if the designated
// constraints aren't met.
type SelectModelResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SelectModelResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SelectModelResponseMultiError) AllErrors() []error { return m }

// SelectModelResponseValidationError is the validation error returned by
// SelectModelResponse.Validate if the designated constraints aren't met.
type SelectModelResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SelectModelResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SelectModelResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SelectModelResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SelectModelResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SelectModelResponseValidationError) ErrorName() string {
	return "SelectModelResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SelectModelResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSelectModelResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SelectModelResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SelectModelResponseValidationError{}

// Validate checks the field values on ValidateOutputRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ValidateOutputRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ValidateOutputRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ValidateOutputRequestMultiError, or nil if none found.
func (m *ValidateOutputRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ValidateOutputRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ModelId

	// no validation rules for Output

	// no validation rules for ExpectedSchema

	// no validation rules for TenantId

	// no validation rules for CorrelationId

	if len(errors) > 0 {
		return ValidateOutputRequestMultiError(errors)
	}

	return nil
}

// ValidateOutputRequestMultiError is an error wrapping multiple validation
// errors returned by ValidateOutputRequest.ValidateAll() if the designated
// constraints aren't met.
type ValidateOutputRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ValidateOutputRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ValidateOutputRequestMultiError) AllErrors() []error { return m }

// ValidateOutputRequestValidationError is the validation error returned by
// ValidateOutputRequest.Validate if the designated constraints aren't met.
type ValidateOutputRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ValidateOutputRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ValidateOutputRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ValidateOutputRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ValidateOutputRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ValidateOutputRequestValidationError) ErrorName() string {
	return "ValidateOutputRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ValidateOutputRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sValidateOutputRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ValidateOutputRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ValidateOutputRequestValidationError{}

// Validate checks the field values on ValidateOutputResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ValidateOutputResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ValidateOutputResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ValidateOutputResponseMultiError, or nil if none found.
func (m *ValidateOutputResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ValidateOutputResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Valid

	// no validation rules for ValidatedOutput

	for idx, item := range m.GetWarnings() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ValidateOutputResponseValidationError{
						field:  fmt.Sprintf("Warnings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ValidateOutputResponseValidationError{
						field:  fmt.Sprintf("Warnings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ValidateOutputResponseValidationError{
					field:  fmt.Sprintf("Warnings[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Error

	if len(errors) > 0 {
		return ValidateOutputResponseMultiError(errors)
	}

	return nil
}

// ValidateOutputResponseMultiError is an error wrapping multiple validation
// errors returned by ValidateOutputResponse.ValidateAll() if the designated
// constraints aren't met.
type ValidateOutputResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ValidateOutputResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ValidateOutputResponseMultiError) AllErrors() []error { return m }

// ValidateOutputResponseValidationError is the validation error returned by
// ValidateOutputResponse.Validate if the designated constraints aren't met.
type ValidateOutputResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ValidateOutputResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ValidateOutputResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ValidateOutputResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ValidateOutputResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ValidateOutputResponseValidationError) ErrorName() string {
	return "ValidateOutputResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ValidateOutputResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sValidateOutputResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ValidateOutputResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ValidateOutputResponseValidationError{}

// Validate checks the field values on ValidationWarning with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ValidationWarning) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ValidationWarning with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ValidationWarningMultiError, or nil if none found.
func (m *ValidationWarning) ValidateAll() error {
	return m.validate(true)
}

func (m *ValidationWarning) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Field

	// no validation rules for Message

	// no validation rules for Severity

	if len(errors) > 0 {
		return ValidationWarningMultiError(errors)
	}

	return nil
}

// ValidationWarningMultiError is an error wrapping multiple validation errors
// returned by ValidationWarning.ValidateAll() if the designated constraints
// aren't met.
type ValidationWarningMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ValidationWarningMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ValidationWarningMultiError) AllErrors() []error { return m }

// ValidationWarningValidationError is the validation error returned by
// ValidationWarning.Validate if the designated constraints aren't met.
type ValidationWarningValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ValidationWarningValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ValidationWarningValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ValidationWarningValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ValidationWarningValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ValidationWarningValidationError) ErrorName() string {
	return "ValidationWarningValidationError"
}

// Error satisfies the builtin error interface
func (e ValidationWarningValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sValidationWarning.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ValidationWarningValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ValidationWarningValidationError{}

// Validate checks the field values on CheckBudgetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckBudgetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckBudgetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckBudgetRequestMultiError, or nil if none found.
func (m *CheckBudgetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckBudgetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for WorkflowId

	// no validation rules for EstimatedTokens

	// no validation rules for ModelId

	if len(errors) > 0 {
		return CheckBudgetRequestMultiError(errors)
	}

	return nil
}

// CheckBudgetRequestMultiError is an error wrapping multiple validation errors
// returned by CheckBudgetRequest.ValidateAll() if the designated constraints
// aren't met.
type CheckBudgetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckBudgetRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckBudgetRequestMultiError) AllErrors() []error { return m }

// CheckBudgetRequestValidationError is the validation error returned by
// CheckBudgetRequest.Validate if the designated constraints aren't met.
type CheckBudgetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckBudgetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckBudgetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckBudgetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckBudgetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckBudgetRequestValidationError) ErrorName() string {
	return "CheckBudgetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CheckBudgetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckBudgetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckBudgetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckBudgetRequestValidationError{}

// Validate checks the field values on CheckBudgetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckBudgetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckBudgetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckBudgetResponseMultiError, or nil if none found.
func (m *CheckBudgetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckBudgetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Allowed

	// no validation rules for RemainingBudget

	// no validation rules for EstimatedCost

	// no validation rules for DenialReason

	if len(errors) > 0 {
		return CheckBudgetResponseMultiError(errors)
	}

	return nil
}

// CheckBudgetResponseMultiError is an error wrapping multiple validation
// errors returned by CheckBudgetResponse.ValidateAll() if the designated
// constraints aren't met.
type CheckBudgetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckBudgetResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckBudgetResponseMultiError) AllErrors() []error { return m }

// CheckBudgetResponseValidationError is the validation error returned by
// CheckBudgetResponse.Validate if the designated constraints aren't met.
type CheckBudgetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckBudgetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckBudgetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckBudgetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckBudgetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckBudgetResponseValidationError) ErrorName() string {
	return "CheckBudgetResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CheckBudgetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckBudgetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckBudgetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckBudgetResponseValidationError{}

// Validate checks the field values on ReleaseBudgetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReleaseBudgetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReleaseBudgetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReleaseBudgetRequestMultiError, or nil if none found.
func (m *ReleaseBudgetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReleaseBudgetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for WorkflowId

	// no validation rules for TokensToRelease

	if len(errors) > 0 {
		return ReleaseBudgetRequestMultiError(errors)
	}

	return nil
}

// ReleaseBudgetRequestMultiError is an error wrapping multiple validation
// errors returned by ReleaseBudgetRequest.ValidateAll() if the designated
// constraints aren't met.
type ReleaseBudgetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReleaseBudgetRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReleaseBudgetRequestMultiError) AllErrors() []error { return m }

// ReleaseBudgetRequestValidationError is the validation error returned by
// ReleaseBudgetRequest.Validate if the designated constraints aren't met.
type ReleaseBudgetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReleaseBudgetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReleaseBudgetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReleaseBudgetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReleaseBudgetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReleaseBudgetRequestValidationError) ErrorName() string {
	return "ReleaseBudgetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ReleaseBudgetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReleaseBudgetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReleaseBudgetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReleaseBudgetRequestValidationError{}

// Validate checks the field values on ReleaseBudgetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReleaseBudgetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReleaseBudgetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReleaseBudgetResponseMultiError, or nil if none found.
func (m *ReleaseBudgetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ReleaseBudgetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for RemainingBudget

	if len(errors) > 0 {
		return ReleaseBudgetResponseMultiError(errors)
	}

	return nil
}

// ReleaseBudgetResponseMultiError is an error wrapping multiple validation
// errors returned by ReleaseBudgetResponse.ValidateAll() if the designated
// constraints aren't met.
type ReleaseBudgetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReleaseBudgetResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReleaseBudgetResponseMultiError) AllErrors() []error { return m }

// ReleaseBudgetResponseValidationError is the validation error returned by
// ReleaseBudgetResponse.Validate if the designated constraints aren't met.
type ReleaseBudgetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReleaseBudgetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReleaseBudgetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReleaseBudgetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReleaseBudgetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReleaseBudgetResponseValidationError) ErrorName() string {
	return "ReleaseBudgetResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ReleaseBudgetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReleaseBudgetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReleaseBudgetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReleaseBudgetResponseValidationError{}

// Validate checks the field values on ModelMetadata with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ModelMetadata) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModelMetadata with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ModelMetadataMultiError, or
// nil if none found.
func (m *ModelMetadata) ValidateAll() error {
	return m.validate(true)
}

func (m *ModelMetadata) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ModelId

	// no validation rules for Provider

	// no validation rules for Name

	// no validation rules for MaxTokens

	// no validation rules for MaxOutputTokens

	// no validation rules for InputCostPer_1K

	// no validation rules for OutputCostPer_1K

	// no validation rules for LatencyP50Ms

	// no validation rules for LatencyP99Ms

	// no validation rules for Available

	// no validation rules for Metadata

	if len(errors) > 0 {
		return ModelMetadataMultiError(errors)
	}

	return nil
}

// ModelMetadataMultiError is an error wrapping multiple validation errors
// returned by ModelMetadata.ValidateAll() if the designated constraints
// aren't met.
type ModelMetadataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModelMetadataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModelMetadataMultiError) AllErrors() []error { return m }

// ModelMetadataValidationError is the validation error returned by
// ModelMetadata.Validate if the designated constraints aren't met.
type ModelMetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModelMetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModelMetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModelMetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModelMetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModelMetadataValidationError) ErrorName() string { return "ModelMetadataValidationError" }

// Error satisfies the builtin error interface
func (e ModelMetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModelMetadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModelMetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModelMetadataValidationError{}

// Validate checks the field values on GetProvidersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetProvidersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetProvidersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetProvidersRequestMultiError, or nil if none found.
func (m *GetProvidersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetProvidersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	if len(errors) > 0 {
		return GetProvidersRequestMultiError(errors)
	}

	return nil
}

// GetProvidersRequestMultiError is an error wrapping multiple validation
// errors returned by GetProvidersRequest.ValidateAll() if the designated
// constraints aren't met.
type GetProvidersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetProvidersRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetProvidersRequestMultiError) AllErrors() []error { return m }

// GetProvidersRequestValidationError is the validation error returned by
// GetProvidersRequest.Validate if the designated constraints aren't met.
type GetProvidersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetProvidersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetProvidersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetProvidersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetProvidersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetProvidersRequestValidationError) ErrorName() string {
	return "GetProvidersRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetProvidersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetProvidersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetProvidersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetProvidersRequestValidationError{}

// Validate checks the field values on GetProvidersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetProvidersResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetProvidersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetProvidersResponseMultiError, or nil if none found.
func (m *GetProvidersResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetProvidersResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetProviders() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetProvidersResponseValidationError{
						field:  fmt.Sprintf("Providers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetProvidersResponseValidationError{
						field:  fmt.Sprintf("Providers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetProvidersResponseValidationError{
					field:  fmt.Sprintf("Providers[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetProvidersResponseMultiError(errors)
	}

	return nil
}

// GetProvidersResponseMultiError is an error wrapping multiple validation
// errors returned by GetProvidersResponse.ValidateAll() if the designated
// constraints aren't met.
type GetProvidersResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetProvidersResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetProvidersResponseMultiError) AllErrors() []error { return m }

// GetProvidersResponseValidationError is the validation error returned by
// GetProvidersResponse.Validate if the designated constraints aren't met.
type GetProvidersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetProvidersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetProvidersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetProvidersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetProvidersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetProvidersResponseValidationError) ErrorName() string {
	return "GetProvidersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetProvidersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetProvidersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetProvidersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetProvidersResponseValidationError{}

// Validate checks the field values on HealthLiveRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *HealthLiveRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthLiveRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthLiveRequestMultiError, or nil if none found.
func (m *HealthLiveRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthLiveRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return HealthLiveRequestMultiError(errors)
	}

	return nil
}

// HealthLiveRequestMultiError is an error wrapping multiple validation errors
// returned by HealthLiveRequest.ValidateAll() if the designated constraints
// aren't met.
type HealthLiveRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthLiveRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthLiveRequestMultiError) AllErrors() []error { return m }

// HealthLiveRequestValidationError is the validation error returned by
// HealthLiveRequest.Validate if the designated constraints aren't met.
type HealthLiveRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthLiveRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthLiveRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthLiveRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthLiveRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthLiveRequestValidationError) ErrorName() string {
	return "HealthLiveRequestValidationError"
}

// Error satisfies the builtin error interface
func (e HealthLiveRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthLiveRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthLiveRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthLiveRequestValidationError{}

// Validate checks the field values on HealthLiveResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HealthLiveResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthLiveResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthLiveResponseMultiError, or nil if none found.
func (m *HealthLiveResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthLiveResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return HealthLiveResponseMultiError(errors)
	}

	return nil
}

// HealthLiveResponseMultiError is an error wrapping multiple validation errors
// returned by HealthLiveResponse.ValidateAll() if the designated constraints
// aren't met.
type HealthLiveResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthLiveResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthLiveResponseMultiError) AllErrors() []error { return m }

// HealthLiveResponseValidationError is the validation error returned by
// HealthLiveResponse.Validate if the designated constraints aren't met.
type HealthLiveResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthLiveResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthLiveResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthLiveResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthLiveResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthLiveResponseValidationError) ErrorName() string {
	return "HealthLiveResponseValidationError"
}

// Error satisfies the builtin error interface
func (e HealthLiveResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthLiveResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthLiveResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthLiveResponseValidationError{}

// Validate checks the field values on HealthReadyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HealthReadyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthReadyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthReadyRequestMultiError, or nil if none found.
func (m *HealthReadyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthReadyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return HealthReadyRequestMultiError(errors)
	}

	return nil
}

// HealthReadyRequestMultiError is an error wrapping multiple validation errors
// returned by HealthReadyRequest.ValidateAll() if the designated constraints
// aren't met.
type HealthReadyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthReadyRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthReadyRequestMultiError) AllErrors() []error { return m }

// HealthReadyRequestValidationError is the validation error returned by
// HealthReadyRequest.Validate if the designated constraints aren't met.
type HealthReadyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthReadyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthReadyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthReadyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthReadyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthReadyRequestValidationError) ErrorName() string {
	return "HealthReadyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e HealthReadyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthReadyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthReadyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthReadyRequestValidationError{}

// Validate checks the field values on HealthReadyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HealthReadyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthReadyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthReadyResponseMultiError, or nil if none found.
func (m *HealthReadyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthReadyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	for idx, item := range m.GetChecks() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HealthReadyResponseValidationError{
						field:  fmt.Sprintf("Checks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HealthReadyResponseValidationError{
						field:  fmt.Sprintf("Checks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HealthReadyResponseValidationError{
					field:  fmt.Sprintf("Checks[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return HealthReadyResponseMultiError(errors)
	}

	return nil
}

// HealthReadyResponseMultiError is an error wrapping multiple validation
// errors returned by HealthReadyResponse.ValidateAll() if the designated
// constraints aren't met.
type HealthReadyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthReadyResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthReadyResponseMultiError) AllErrors() []error { return m }

// HealthReadyResponseValidationError is the validation error returned by
// HealthReadyResponse.Validate if the designated constraints aren't met.
type HealthReadyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthReadyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthReadyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthReadyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthReadyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthReadyResponseValidationError) ErrorName() string {
	return "HealthReadyResponseValidationError"
}

// Error satisfies the builtin error interface
func (e HealthReadyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthReadyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthReadyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthReadyResponseValidationError{}
