// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/proto/gix/workflow/v1/workflow.proto

package workflowv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on StartExecutionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StartExecutionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StartExecutionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StartExecutionRequestMultiError, or nil if none found.
func (m *StartExecutionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *StartExecutionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for WorkflowId

	if all {
		switch v := interface{}(m.GetWorkflow()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, StartExecutionRequestValidationError{
					field:  "Workflow",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, StartExecutionRequestValidationError{
					field:  "Workflow",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetWorkflow()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StartExecutionRequestValidationError{
				field:  "Workflow",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Input

	for idx, item := range m.GetCapabilities() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, StartExecutionRequestValidationError{
						field:  fmt.Sprintf("Capabilities[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, StartExecutionRequestValidationError{
						field:  fmt.Sprintf("Capabilities[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return StartExecutionRequestValidationError{
					field:  fmt.Sprintf("Capabilities[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for IdempotencyKey

	if len(errors) > 0 {
		return StartExecutionRequestMultiError(errors)
	}

	return nil
}

// StartExecutionRequestMultiError is an error wrapping multiple validation
// errors returned by StartExecutionRequest.ValidateAll() if the designated
// constraints aren't met.
type StartExecutionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StartExecutionRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StartExecutionRequestMultiError) AllErrors() []error { return m }

// StartExecutionRequestValidationError is the validation error returned by
// StartExecutionRequest.Validate if the designated constraints aren't met.
type StartExecutionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StartExecutionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StartExecutionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StartExecutionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StartExecutionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StartExecutionRequestValidationError) ErrorName() string {
	return "StartExecutionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e StartExecutionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStartExecutionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StartExecutionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StartExecutionRequestValidationError{}

// Validate checks the field values on WorkflowDefinition with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *WorkflowDefinition) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WorkflowDefinition with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WorkflowDefinitionMultiError, or nil if none found.
func (m *WorkflowDefinition) ValidateAll() error {
	return m.validate(true)
}

func (m *WorkflowDefinition) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Version

	for idx, item := range m.GetSteps() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WorkflowDefinitionValidationError{
						field:  fmt.Sprintf("Steps[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WorkflowDefinitionValidationError{
						field:  fmt.Sprintf("Steps[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WorkflowDefinitionValidationError{
					field:  fmt.Sprintf("Steps[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TimeoutSeconds

	// no validation rules for Metadata

	if len(errors) > 0 {
		return WorkflowDefinitionMultiError(errors)
	}

	return nil
}

// WorkflowDefinitionMultiError is an error wrapping multiple validation errors
// returned by WorkflowDefinition.ValidateAll() if the designated constraints
// aren't met.
type WorkflowDefinitionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WorkflowDefinitionMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WorkflowDefinitionMultiError) AllErrors() []error { return m }

// WorkflowDefinitionValidationError is the validation error returned by
// WorkflowDefinition.Validate if the designated constraints aren't met.
type WorkflowDefinitionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WorkflowDefinitionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WorkflowDefinitionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WorkflowDefinitionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WorkflowDefinitionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WorkflowDefinitionValidationError) ErrorName() string {
	return "WorkflowDefinitionValidationError"
}

// Error satisfies the builtin error interface
func (e WorkflowDefinitionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWorkflowDefinition.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WorkflowDefinitionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WorkflowDefinitionValidationError{}

// Validate checks the field values on WorkflowStep with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WorkflowStep) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WorkflowStep with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WorkflowStepMultiError, or
// nil if none found.
func (m *WorkflowStep) ValidateAll() error {
	return m.validate(true)
}

func (m *WorkflowStep) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Type

	// no validation rules for Action

	// no validation rules for Input

	// no validation rules for Output

	// no validation rules for Condition

	// no validation rules for TimeoutSeconds

	if all {
		switch v := interface{}(m.GetRetry()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WorkflowStepValidationError{
					field:  "Retry",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WorkflowStepValidationError{
					field:  "Retry",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRetry()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WorkflowStepValidationError{
				field:  "Retry",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for OnFailure

	if len(errors) > 0 {
		return WorkflowStepMultiError(errors)
	}

	return nil
}

// WorkflowStepMultiError is an error wrapping multiple validation errors
// returned by WorkflowStep.ValidateAll() if the designated constraints aren't met.
type WorkflowStepMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WorkflowStepMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WorkflowStepMultiError) AllErrors() []error { return m }

// WorkflowStepValidationError is the validation error returned by
// WorkflowStep.Validate if the designated constraints aren't met.
type WorkflowStepValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WorkflowStepValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WorkflowStepValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WorkflowStepValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WorkflowStepValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WorkflowStepValidationError) ErrorName() string { return "WorkflowStepValidationError" }

// Error satisfies the builtin error interface
func (e WorkflowStepValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWorkflowStep.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WorkflowStepValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WorkflowStepValidationError{}

// Validate checks the field values on RetryPolicy with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RetryPolicy) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RetryPolicy with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RetryPolicyMultiError, or
// nil if none found.
func (m *RetryPolicy) ValidateAll() error {
	return m.validate(true)
}

func (m *RetryPolicy) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MaxAttempts

	// no validation rules for IntervalSeconds

	// no validation rules for Backoff

	// no validation rules for MaxIntervalSeconds

	if len(errors) > 0 {
		return RetryPolicyMultiError(errors)
	}

	return nil
}

// RetryPolicyMultiError is an error wrapping multiple validation errors
// returned by RetryPolicy.ValidateAll() if the designated constraints aren't met.
type RetryPolicyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RetryPolicyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RetryPolicyMultiError) AllErrors() []error { return m }

// RetryPolicyValidationError is the validation error returned by
// RetryPolicy.Validate if the designated constraints aren't met.
type RetryPolicyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RetryPolicyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RetryPolicyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RetryPolicyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RetryPolicyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RetryPolicyValidationError) ErrorName() string { return "RetryPolicyValidationError" }

// Error satisfies the builtin error interface
func (e RetryPolicyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRetryPolicy.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RetryPolicyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RetryPolicyValidationError{}

// Validate checks the field values on StartExecutionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StartExecutionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StartExecutionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StartExecutionResponseMultiError, or nil if none found.
func (m *StartExecutionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *StartExecutionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ExecutionId

	// no validation rules for Status

	// no validation rules for ErrorCode

	// no validation rules for ErrorMessage

	if len(errors) > 0 {
		return StartExecutionResponseMultiError(errors)
	}

	return nil
}

// StartExecutionResponseMultiError is an error wrapping multiple validation
// errors returned by StartExecutionResponse.ValidateAll() if the designated
// constraints aren't met.
type StartExecutionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StartExecutionResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StartExecutionResponseMultiError) AllErrors() []error { return m }

// StartExecutionResponseValidationError is the validation error returned by
// StartExecutionResponse.Validate if the designated constraints aren't met.
type StartExecutionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StartExecutionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StartExecutionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StartExecutionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StartExecutionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StartExecutionResponseValidationError) ErrorName() string {
	return "StartExecutionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e StartExecutionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStartExecutionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StartExecutionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StartExecutionResponseValidationError{}

// Validate checks the field values on GetExecutionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetExecutionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetExecutionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetExecutionRequestMultiError, or nil if none found.
func (m *GetExecutionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetExecutionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ExecutionId

	if len(errors) > 0 {
		return GetExecutionRequestMultiError(errors)
	}

	return nil
}

// GetExecutionRequestMultiError is an error wrapping multiple validation
// errors returned by GetExecutionRequest.ValidateAll() if the designated
// constraints aren't met.
type GetExecutionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetExecutionRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetExecutionRequestMultiError) AllErrors() []error { return m }

// GetExecutionRequestValidationError is the validation error returned by
// GetExecutionRequest.Validate if the designated constraints aren't met.
type GetExecutionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetExecutionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetExecutionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetExecutionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetExecutionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetExecutionRequestValidationError) ErrorName() string {
	return "GetExecutionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetExecutionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetExecutionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetExecutionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetExecutionRequestValidationError{}

// Validate checks the field values on GetExecutionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetExecutionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetExecutionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetExecutionResponseMultiError, or nil if none found.
func (m *GetExecutionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetExecutionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetExecution()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetExecutionResponseValidationError{
					field:  "Execution",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetExecutionResponseValidationError{
					field:  "Execution",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExecution()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetExecutionResponseValidationError{
				field:  "Execution",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetExecutionResponseMultiError(errors)
	}

	return nil
}

// GetExecutionResponseMultiError is an error wrapping multiple validation
// errors returned by GetExecutionResponse.ValidateAll() if the designated
// constraints aren't met.
type GetExecutionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetExecutionResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetExecutionResponseMultiError) AllErrors() []error { return m }

// GetExecutionResponseValidationError is the validation error returned by
// GetExecutionResponse.Validate if the designated constraints aren't met.
type GetExecutionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetExecutionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetExecutionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetExecutionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetExecutionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetExecutionResponseValidationError) ErrorName() string {
	return "GetExecutionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetExecutionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetExecutionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetExecutionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetExecutionResponseValidationError{}

// Validate checks the field values on CancelExecutionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CancelExecutionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CancelExecutionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CancelExecutionRequestMultiError, or nil if none found.
func (m *CancelExecutionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CancelExecutionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ExecutionId

	if len(errors) > 0 {
		return CancelExecutionRequestMultiError(errors)
	}

	return nil
}

// CancelExecutionRequestMultiError is an error wrapping multiple validation
// errors returned by CancelExecutionRequest.ValidateAll() if the designated
// constraints aren't met.
type CancelExecutionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CancelExecutionRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CancelExecutionRequestMultiError) AllErrors() []error { return m }

// CancelExecutionRequestValidationError is the validation error returned by
// CancelExecutionRequest.Validate if the designated constraints aren't met.
type CancelExecutionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CancelExecutionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CancelExecutionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CancelExecutionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CancelExecutionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CancelExecutionRequestValidationError) ErrorName() string {
	return "CancelExecutionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CancelExecutionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCancelExecutionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CancelExecutionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CancelExecutionRequestValidationError{}

// Validate checks the field values on CancelExecutionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CancelExecutionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CancelExecutionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CancelExecutionResponseMultiError, or nil if none found.
func (m *CancelExecutionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CancelExecutionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	if len(errors) > 0 {
		return CancelExecutionResponseMultiError(errors)
	}

	return nil
}

// CancelExecutionResponseMultiError is an error wrapping multiple validation
// errors returned by CancelExecutionResponse.ValidateAll() if the designated
// constraints aren't met.
type CancelExecutionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CancelExecutionResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CancelExecutionResponseMultiError) AllErrors() []error { return m }

// CancelExecutionResponseValidationError is the validation error returned by
// CancelExecutionResponse.Validate if the designated constraints aren't met.
type CancelExecutionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CancelExecutionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CancelExecutionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CancelExecutionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CancelExecutionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CancelExecutionResponseValidationError) ErrorName() string {
	return "CancelExecutionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CancelExecutionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCancelExecutionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CancelExecutionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CancelExecutionResponseValidationError{}

// Validate checks the field values on ExecutionRecord with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ExecutionRecord) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExecutionRecord with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExecutionRecordMultiError, or nil if none found.
func (m *ExecutionRecord) ValidateAll() error {
	return m.validate(true)
}

func (m *ExecutionRecord) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ExecutionId

	// no validation rules for WorkflowId

	// no validation rules for WorkflowType

	// no validation rules for Status

	// no validation rules for Input

	// no validation rules for Output

	// no validation rules for ErrorCode

	// no validation rules for ErrorMessage

	// no validation rules for StartedAt

	// no validation rules for CompletedAt

	// no validation rules for CorrelationId

	// no validation rules for TenantId

	if len(errors) > 0 {
		return ExecutionRecordMultiError(errors)
	}

	return nil
}

// ExecutionRecordMultiError is an error wrapping multiple validation errors
// returned by ExecutionRecord.ValidateAll() if the designated constraints
// aren't met.
type ExecutionRecordMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExecutionRecordMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExecutionRecordMultiError) AllErrors() []error { return m }

// ExecutionRecordValidationError is the validation error returned by
// ExecutionRecord.Validate if the designated constraints aren't met.
type ExecutionRecordValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExecutionRecordValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExecutionRecordValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExecutionRecordValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExecutionRecordValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExecutionRecordValidationError) ErrorName() string { return "ExecutionRecordValidationError" }

// Error satisfies the builtin error interface
func (e ExecutionRecordValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExecutionRecord.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExecutionRecordValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExecutionRecordValidationError{}

// Validate checks the field values on ListExecutionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListExecutionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListExecutionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListExecutionsRequestMultiError, or nil if none found.
func (m *ListExecutionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListExecutionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for WorkflowId

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListExecutionsRequestValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListExecutionsRequestValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListExecutionsRequestValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for TenantId

	if len(errors) > 0 {
		return ListExecutionsRequestMultiError(errors)
	}

	return nil
}

// ListExecutionsRequestMultiError is an error wrapping multiple validation
// errors returned by ListExecutionsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListExecutionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListExecutionsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListExecutionsRequestMultiError) AllErrors() []error { return m }

// ListExecutionsRequestValidationError is the validation error returned by
// ListExecutionsRequest.Validate if the designated constraints aren't met.
type ListExecutionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListExecutionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListExecutionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListExecutionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListExecutionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListExecutionsRequestValidationError) ErrorName() string {
	return "ListExecutionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListExecutionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListExecutionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListExecutionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListExecutionsRequestValidationError{}

// Validate checks the field values on ListExecutionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListExecutionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListExecutionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListExecutionsResponseMultiError, or nil if none found.
func (m *ListExecutionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListExecutionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetExecutions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListExecutionsResponseValidationError{
						field:  fmt.Sprintf("Executions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListExecutionsResponseValidationError{
						field:  fmt.Sprintf("Executions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListExecutionsResponseValidationError{
					field:  fmt.Sprintf("Executions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListExecutionsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListExecutionsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListExecutionsResponseValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListExecutionsResponseMultiError(errors)
	}

	return nil
}

// ListExecutionsResponseMultiError is an error wrapping multiple validation
// errors returned by ListExecutionsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListExecutionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListExecutionsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListExecutionsResponseMultiError) AllErrors() []error { return m }

// ListExecutionsResponseValidationError is the validation error returned by
// ListExecutionsResponse.Validate if the designated constraints aren't met.
type ListExecutionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListExecutionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListExecutionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListExecutionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListExecutionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListExecutionsResponseValidationError) ErrorName() string {
	return "ListExecutionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListExecutionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListExecutionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListExecutionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListExecutionsResponseValidationError{}
