// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: api/proto/gix/audit/v1/audit.proto

package auditv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AuditService_LogEvent_FullMethodName        = "/gix.audit.v1.AuditService/LogEvent"
	AuditService_QueryEvents_FullMethodName     = "/gix.audit.v1.AuditService/QueryEvents"
	AuditService_VerifyIntegrity_FullMethodName = "/gix.audit.v1.AuditService/VerifyIntegrity"
	AuditService_HealthLive_FullMethodName      = "/gix.audit.v1.AuditService/HealthLive"
	AuditService_HealthReady_FullMethodName     = "/gix.audit.v1.AuditService/HealthReady"
)

// AuditServiceClient is the client API for AuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditServiceClient interface {
	LogEvent(ctx context.Context, in *LogEventRequest, opts ...grpc.CallOption) (*LogEventResponse, error)
	QueryEvents(ctx context.Context, in *QueryEventsRequest, opts ...grpc.CallOption) (*QueryEventsResponse, error)
	VerifyIntegrity(ctx context.Context, in *VerifyIntegrityRequest, opts ...grpc.CallOption) (*VerifyIntegrityResponse, error)
	HealthLive(ctx context.Context, in *HealthLiveRequest, opts ...grpc.CallOption) (*HealthLiveResponse, error)
	HealthReady(ctx context.Context, in *HealthReadyRequest, opts ...grpc.CallOption) (*HealthReadyResponse, error)
}

type auditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditServiceClient(cc grpc.ClientConnInterface) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) LogEvent(ctx context.Context, in *LogEventRequest, opts ...grpc.CallOption) (*LogEventResponse, error) {
	out := new(LogEventResponse)
	err := c.cc.Invoke(ctx, AuditService_LogEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) QueryEvents(ctx context.Context, in *QueryEventsRequest, opts ...grpc.CallOption) (*QueryEventsResponse, error) {
	out := new(QueryEventsResponse)
	err := c.cc.Invoke(ctx, AuditService_QueryEvents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) VerifyIntegrity(ctx context.Context, in *VerifyIntegrityRequest, opts ...grpc.CallOption) (*VerifyIntegrityResponse, error) {
	out := new(VerifyIntegrityResponse)
	err := c.cc.Invoke(ctx, AuditService_VerifyIntegrity_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) HealthLive(ctx context.Context, in *HealthLiveRequest, opts ...grpc.CallOption) (*HealthLiveResponse, error) {
	out := new(HealthLiveResponse)
	err := c.cc.Invoke(ctx, AuditService_HealthLive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) HealthReady(ctx context.Context, in *HealthReadyRequest, opts ...grpc.CallOption) (*HealthReadyResponse, error) {
	out := new(HealthReadyResponse)
	err := c.cc.Invoke(ctx, AuditService_HealthReady_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditServiceServer is the server API for AuditService service.
// All implementations must embed UnimplementedAuditServiceServer
// for forward compatibility
type AuditServiceServer interface {
	LogEvent(context.Context, *LogEventRequest) (*LogEventResponse, error)
	QueryEvents(context.Context, *QueryEventsRequest) (*QueryEventsResponse, error)
	VerifyIntegrity(context.Context, *VerifyIntegrityRequest) (*VerifyIntegrityResponse, error)
	HealthLive(context.Context, *HealthLiveRequest) (*HealthLiveResponse, error)
	HealthReady(context.Context, *HealthReadyRequest) (*HealthReadyResponse, error)
	mustEmbedUnimplementedAuditServiceServer()
}

// UnimplementedAuditServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuditServiceServer struct {
}

func (UnimplementedAuditServiceServer) LogEvent(context.Context, *LogEventRequest) (*LogEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogEvent not implemented")
}
func (UnimplementedAuditServiceServer) QueryEvents(context.Context, *QueryEventsRequest) (*QueryEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryEvents not implemented")
}
func (UnimplementedAuditServiceServer) VerifyIntegrity(context.Context, *VerifyIntegrityRequest) (*VerifyIntegrityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyIntegrity not implemented")
}
func (UnimplementedAuditServiceServer) HealthLive(context.Context, *HealthLiveRequest) (*HealthLiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthLive not implemented")
}
func (UnimplementedAuditServiceServer) HealthReady(context.Context, *HealthReadyRequest) (*HealthReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthReady not implemented")
}
func (UnimplementedAuditServiceServer) mustEmbedUnimplementedAuditServiceServer() {}

// UnsafeAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditServiceServer will
// result in compilation errors.
type UnsafeAuditServiceServer interface {
	mustEmbedUnimplementedAuditServiceServer()
}

func RegisterAuditServiceServer(s grpc.ServiceRegistrar, srv AuditServiceServer) {
	s.RegisterService(&AuditService_ServiceDesc, srv)
}

func _AuditService_LogEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).LogEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_LogEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).LogEvent(ctx, req.(*LogEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_QueryEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).QueryEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_QueryEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).QueryEvents(ctx, req.(*QueryEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_VerifyIntegrity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyIntegrityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).VerifyIntegrity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_VerifyIntegrity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).VerifyIntegrity(ctx, req.(*VerifyIntegrityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_HealthLive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthLiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).HealthLive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_HealthLive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).HealthLive(ctx, req.(*HealthLiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_HealthReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).HealthReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_HealthReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).HealthReady(ctx, req.(*HealthReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditService_ServiceDesc is the grpc.ServiceDesc for AuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gix.audit.v1.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogEvent",
			Handler:    _AuditService_LogEvent_Handler,
		},
		{
			MethodName: "QueryEvents",
			Handler:    _AuditService_QueryEvents_Handler,
		},
		{
			MethodName: "VerifyIntegrity",
			Handler:    _AuditService_VerifyIntegrity_Handler,
		},
		{
			MethodName: "HealthLive",
			Handler:    _AuditService_HealthLive_Handler,
		},
		{
			MethodName: "HealthReady",
			Handler:    _AuditService_HealthReady_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/gix/audit/v1/audit.proto",
}
