// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/proto/gix/audit/v1/audit.proto

package auditv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on LogEventRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *LogEventRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LogEventRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LogEventRequestMultiError, or nil if none found.
func (m *LogEventRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *LogEventRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetEvent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LogEventRequestValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LogEventRequestValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEvent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LogEventRequestValidationError{
				field:  "Event",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return LogEventRequestMultiError(errors)
	}

	return nil
}

// LogEventRequestMultiError is an error wrapping multiple validation errors
// returned by LogEventRequest.ValidateAll() if the designated constraints
// aren't met.
type LogEventRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LogEventRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LogEventRequestMultiError) AllErrors() []error { return m }

// LogEventRequestValidationError is the validation error returned by
// LogEventRequest.Validate if the designated constraints aren't met.
type LogEventRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LogEventRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LogEventRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LogEventRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LogEventRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LogEventRequestValidationError) ErrorName() string { return "LogEventRequestValidationError" }

// Error satisfies the builtin error interface
func (e LogEventRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLogEventRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LogEventRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LogEventRequestValidationError{}

// Validate checks the field values on LogEventResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *LogEventResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LogEventResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LogEventResponseMultiError, or nil if none found.
func (m *LogEventResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *LogEventResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EventId

	// no validation rules for Accepted

	if len(errors) > 0 {
		return LogEventResponseMultiError(errors)
	}

	return nil
}

// LogEventResponseMultiError is an error wrapping multiple validation errors
// returned by LogEventResponse.ValidateAll() if the designated constraints
// aren't met.
type LogEventResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LogEventResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LogEventResponseMultiError) AllErrors() []error { return m }

// LogEventResponseValidationError is the validation error returned by
// LogEventResponse.Validate if the designated constraints aren't met.
type LogEventResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LogEventResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LogEventResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LogEventResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LogEventResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LogEventResponseValidationError) ErrorName() string { return "LogEventResponseValidationError" }

// Error satisfies the builtin error interface
func (e LogEventResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLogEventResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LogEventResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LogEventResponseValidationError{}

// Validate checks the field values on QueryEventsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryEventsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryEventsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryEventsRequestMultiError, or nil if none found.
func (m *QueryEventsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryEventsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for StartTime

	// no validation rules for EndTime

	// no validation rules for TenantId

	// no validation rules for EventType

	// no validation rules for ActorId

	// no validation rules for ResourceType

	// no validation rules for ResourceId

	// no validation rules for Outcome

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueryEventsRequestValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueryEventsRequestValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueryEventsRequestValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return QueryEventsRequestMultiError(errors)
	}

	return nil
}

// QueryEventsRequestMultiError is an error wrapping multiple validation errors
// returned by QueryEventsRequest.ValidateAll() if the designated constraints
// aren't met.
type QueryEventsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryEventsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryEventsRequestMultiError) AllErrors() []error { return m }

// QueryEventsRequestValidationError is the validation error returned by
// QueryEventsRequest.Validate if the designated constraints aren't met.
type QueryEventsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryEventsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryEventsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryEventsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryEventsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryEventsRequestValidationError) ErrorName() string {
	return "QueryEventsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e QueryEventsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryEventsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryEventsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryEventsRequestValidationError{}

// Validate checks the field values on QueryEventsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryEventsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryEventsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryEventsResponseMultiError, or nil if none found.
func (m *QueryEventsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryEventsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetEvents() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QueryEventsResponseValidationError{
						field:  fmt.Sprintf("Events[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QueryEventsResponseValidationError{
						field:  fmt.Sprintf("Events[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QueryEventsResponseValidationError{
					field:  fmt.Sprintf("Events[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueryEventsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueryEventsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueryEventsResponseValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return QueryEventsResponseMultiError(errors)
	}

	return nil
}

// QueryEventsResponseMultiError is an error wrapping multiple validation
// errors returned by QueryEventsResponse.ValidateAll() if the designated
// constraints aren't met.
type QueryEventsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryEventsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryEventsResponseMultiError) AllErrors() []error { return m }

// QueryEventsResponseValidationError is the validation error returned by
// QueryEventsResponse.Validate if the designated constraints aren't met.
type QueryEventsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryEventsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryEventsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryEventsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryEventsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryEventsResponseValidationError) ErrorName() string {
	return "QueryEventsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e QueryEventsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryEventsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryEventsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryEventsResponseValidationError{}

// Validate checks the field values on VerifyIntegrityRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *VerifyIntegrityRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VerifyIntegrityRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VerifyIntegrityRequestMultiError, or nil if none found.
func (m *VerifyIntegrityRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *VerifyIntegrityRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for StartEventId

	// no validation rules for EndEventId

	if len(errors) > 0 {
		return VerifyIntegrityRequestMultiError(errors)
	}

	return nil
}

// VerifyIntegrityRequestMultiError is an error wrapping multiple validation
// errors returned by VerifyIntegrityRequest.ValidateAll() if the designated
// constraints aren't met.
type VerifyIntegrityRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VerifyIntegrityRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VerifyIntegrityRequestMultiError) AllErrors() []error { return m }

// VerifyIntegrityRequestValidationError is the validation error returned by
// VerifyIntegrityRequest.Validate if the designated constraints aren't met.
type VerifyIntegrityRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VerifyIntegrityRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VerifyIntegrityRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VerifyIntegrityRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VerifyIntegrityRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VerifyIntegrityRequestValidationError) ErrorName() string {
	return "VerifyIntegrityRequestValidationError"
}

// Error satisfies the builtin error interface
func (e VerifyIntegrityRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVerifyIntegrityRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VerifyIntegrityRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VerifyIntegrityRequestValidationError{}

// Validate checks the field values on VerifyIntegrityResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *VerifyIntegrityResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VerifyIntegrityResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VerifyIntegrityResponseMultiError, or nil if none found.
func (m *VerifyIntegrityResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *VerifyIntegrityResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Valid

	// no validation rules for Error

	// no validation rules for CheckedEvents

	if len(errors) > 0 {
		return VerifyIntegrityResponseMultiError(errors)
	}

	return nil
}

// VerifyIntegrityResponseMultiError is an error wrapping multiple validation
// errors returned by VerifyIntegrityResponse.ValidateAll() if the designated
// constraints aren't met.
type VerifyIntegrityResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VerifyIntegrityResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VerifyIntegrityResponseMultiError) AllErrors() []error { return m }

// VerifyIntegrityResponseValidationError is the validation error returned by
// VerifyIntegrityResponse.Validate if the designated constraints aren't met.
type VerifyIntegrityResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VerifyIntegrityResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VerifyIntegrityResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VerifyIntegrityResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VerifyIntegrityResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VerifyIntegrityResponseValidationError) ErrorName() string {
	return "VerifyIntegrityResponseValidationError"
}

// Error satisfies the builtin error interface
func (e VerifyIntegrityResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVerifyIntegrityResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VerifyIntegrityResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VerifyIntegrityResponseValidationError{}

// Validate checks the field values on AuditEvent with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AuditEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuditEvent with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AuditEventMultiError, or
// nil if none found.
func (m *AuditEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *AuditEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EventId

	// no validation rules for Timestamp

	// no validation rules for EventType

	if all {
		switch v := interface{}(m.GetActor()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuditEventValidationError{
					field:  "Actor",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuditEventValidationError{
					field:  "Actor",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetActor()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuditEventValidationError{
				field:  "Actor",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetResource()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuditEventValidationError{
					field:  "Resource",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuditEventValidationError{
					field:  "Resource",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResource()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuditEventValidationError{
				field:  "Resource",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Action

	// no validation rules for Outcome

	// no validation rules for Details

	if all {
		switch v := interface{}(m.GetSecurityContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuditEventValidationError{
					field:  "SecurityContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuditEventValidationError{
					field:  "SecurityContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSecurityContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuditEventValidationError{
				field:  "SecurityContext",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetIntegrity()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuditEventValidationError{
					field:  "Integrity",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuditEventValidationError{
					field:  "Integrity",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetIntegrity()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuditEventValidationError{
				field:  "Integrity",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AuditEventMultiError(errors)
	}

	return nil
}

// AuditEventMultiError is an error wrapping multiple validation errors
// returned by AuditEvent.ValidateAll() if the designated constraints aren't met.
type AuditEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuditEventMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuditEventMultiError) AllErrors() []error { return m }

// AuditEventValidationError is the validation error returned by
// AuditEvent.Validate if the designated constraints aren't met.
type AuditEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuditEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuditEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuditEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuditEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuditEventValidationError) ErrorName() string { return "AuditEventValidationError" }

// Error satisfies the builtin error interface
func (e AuditEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuditEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuditEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuditEventValidationError{}

// Validate checks the field values on Actor with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Actor) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Actor with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ActorMultiError, or nil if none found.
func (m *Actor) ValidateAll() error {
	return m.validate(true)
}

func (m *Actor) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for Id

	// no validation rules for TenantId

	if len(errors) > 0 {
		return ActorMultiError(errors)
	}

	return nil
}

// ActorMultiError is an error wrapping multiple validation errors returned by
// Actor.ValidateAll() if the designated constraints aren't met.
type ActorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ActorMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ActorMultiError) AllErrors() []error { return m }

// ActorValidationError is the validation error returned by Actor.Validate if
// the designated constraints aren't met.
type ActorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ActorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ActorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ActorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ActorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ActorValidationError) ErrorName() string { return "ActorValidationError" }

// Error satisfies the builtin error interface
func (e ActorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sActor.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ActorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ActorValidationError{}

// Validate checks the field values on Resource with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Resource) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Resource with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ResourceMultiError, or nil
// if none found.
func (m *Resource) ValidateAll() error {
	return m.validate(true)
}

func (m *Resource) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for Id

	// no validation rules for TenantId

	if len(errors) > 0 {
		return ResourceMultiError(errors)
	}

	return nil
}

// ResourceMultiError is an error wrapping multiple validation errors returned
// by Resource.ValidateAll() if the designated constraints aren't met.
type ResourceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceMultiError) AllErrors() []error { return m }

// ResourceValidationError is the validation error returned by
// Resource.Validate if the designated constraints aren't met.
type ResourceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceValidationError) ErrorName() string { return "ResourceValidationError" }

// Error satisfies the builtin error interface
func (e ResourceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResource.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceValidationError{}

// Validate checks the field values on SecurityContext with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SecurityContext) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SecurityContext with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SecurityContextMultiError, or nil if none found.
func (m *SecurityContext) ValidateAll() error {
	return m.validate(true)
}

func (m *SecurityContext) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SourceIp

	// no validation rules for UserAgent

	if len(errors) > 0 {
		return SecurityContextMultiError(errors)
	}

	return nil
}

// SecurityContextMultiError is an error wrapping multiple validation errors
// returned by SecurityContext.ValidateAll() if the designated constraints
// aren't met.
type SecurityContextMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SecurityContextMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SecurityContextMultiError) AllErrors() []error { return m }

// SecurityContextValidationError is the validation error returned by
// SecurityContext.Validate if the designated constraints aren't met.
type SecurityContextValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SecurityContextValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SecurityContextValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SecurityContextValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SecurityContextValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SecurityContextValidationError) ErrorName() string { return "SecurityContextValidationError" }

// Error satisfies the builtin error interface
func (e SecurityContextValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSecurityContext.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SecurityContextValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SecurityContextValidationError{}

// Validate checks the field values on Integrity with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Integrity) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Integrity with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in IntegrityMultiError, or nil
// if none found.
func (m *Integrity) ValidateAll() error {
	return m.validate(true)
}

func (m *Integrity) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PrevHash

	// no validation rules for Hash

	if len(errors) > 0 {
		return IntegrityMultiError(errors)
	}

	return nil
}

// IntegrityMultiError is an error wrapping multiple validation errors returned
// by Integrity.ValidateAll() if the designated constraints aren't met.
type IntegrityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IntegrityMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IntegrityMultiError) AllErrors() []error { return m }

// IntegrityValidationError is the validation error returned by
// Integrity.Validate if the designated constraints aren't met.
type IntegrityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IntegrityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IntegrityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IntegrityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IntegrityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IntegrityValidationError) ErrorName() string { return "IntegrityValidationError" }

// Error satisfies the builtin error interface
func (e IntegrityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIntegrity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IntegrityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IntegrityValidationError{}

// Validate checks the field values on HealthLiveRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *HealthLiveRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthLiveRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthLiveRequestMultiError, or nil if none found.
func (m *HealthLiveRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthLiveRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return HealthLiveRequestMultiError(errors)
	}

	return nil
}

// HealthLiveRequestMultiError is an error wrapping multiple validation errors
// returned by HealthLiveRequest.ValidateAll() if the designated constraints
// aren't met.
type HealthLiveRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthLiveRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthLiveRequestMultiError) AllErrors() []error { return m }

// HealthLiveRequestValidationError is the validation error returned by
// HealthLiveRequest.Validate if the designated constraints aren't met.
type HealthLiveRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthLiveRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthLiveRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthLiveRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthLiveRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthLiveRequestValidationError) ErrorName() string {
	return "HealthLiveRequestValidationError"
}

// Error satisfies the builtin error interface
func (e HealthLiveRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthLiveRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthLiveRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthLiveRequestValidationError{}

// Validate checks the field values on HealthLiveResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HealthLiveResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthLiveResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthLiveResponseMultiError, or nil if none found.
func (m *HealthLiveResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthLiveResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return HealthLiveResponseMultiError(errors)
	}

	return nil
}

// HealthLiveResponseMultiError is an error wrapping multiple validation errors
// returned by HealthLiveResponse.ValidateAll() if the designated constraints
// aren't met.
type HealthLiveResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthLiveResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthLiveResponseMultiError) AllErrors() []error { return m }

// HealthLiveResponseValidationError is the validation error returned by
// HealthLiveResponse.Validate if the designated constraints aren't met.
type HealthLiveResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthLiveResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthLiveResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthLiveResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthLiveResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthLiveResponseValidationError) ErrorName() string {
	return "HealthLiveResponseValidationError"
}

// Error satisfies the builtin error interface
func (e HealthLiveResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthLiveResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthLiveResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthLiveResponseValidationError{}

// Validate checks the field values on HealthReadyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HealthReadyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthReadyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthReadyRequestMultiError, or nil if none found.
func (m *HealthReadyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthReadyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return HealthReadyRequestMultiError(errors)
	}

	return nil
}

// HealthReadyRequestMultiError is an error wrapping multiple validation errors
// returned by HealthReadyRequest.ValidateAll() if the designated constraints
// aren't met.
type HealthReadyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthReadyRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthReadyRequestMultiError) AllErrors() []error { return m }

// HealthReadyRequestValidationError is the validation error returned by
// HealthReadyRequest.Validate if the designated constraints aren't met.
type HealthReadyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthReadyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthReadyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthReadyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthReadyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthReadyRequestValidationError) ErrorName() string {
	return "HealthReadyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e HealthReadyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthReadyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthReadyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthReadyRequestValidationError{}

// Validate checks the field values on HealthReadyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HealthReadyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthReadyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthReadyResponseMultiError, or nil if none found.
func (m *HealthReadyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthReadyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	for idx, item := range m.GetChecks() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HealthReadyResponseValidationError{
						field:  fmt.Sprintf("Checks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HealthReadyResponseValidationError{
						field:  fmt.Sprintf("Checks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HealthReadyResponseValidationError{
					field:  fmt.Sprintf("Checks[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return HealthReadyResponseMultiError(errors)
	}

	return nil
}

// HealthReadyResponseMultiError is an error wrapping multiple validation
// errors returned by HealthReadyResponse.ValidateAll() if the designated
// constraints aren't met.
type HealthReadyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthReadyResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthReadyResponseMultiError) AllErrors() []error { return m }

// HealthReadyResponseValidationError is the validation error returned by
// HealthReadyResponse.Validate if the designated constraints aren't met.
type HealthReadyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthReadyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthReadyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthReadyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthReadyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthReadyResponseValidationError) ErrorName() string {
	return "HealthReadyResponseValidationError"
}

// Error satisfies the builtin error interface
func (e HealthReadyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthReadyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthReadyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthReadyResponseValidationError{}
