// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/proto/gix/harness/v1/harness.proto

package harnessv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SpawnAgentRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SpawnAgentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SpawnAgentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SpawnAgentRequestMultiError, or nil if none found.
func (m *SpawnAgentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SpawnAgentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAgent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SpawnAgentRequestValidationError{
					field:  "Agent",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SpawnAgentRequestValidationError{
					field:  "Agent",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAgent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SpawnAgentRequestValidationError{
				field:  "Agent",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetCapabilityGrants() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SpawnAgentRequestValidationError{
						field:  fmt.Sprintf("CapabilityGrants[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SpawnAgentRequestValidationError{
						field:  fmt.Sprintf("CapabilityGrants[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SpawnAgentRequestValidationError{
					field:  fmt.Sprintf("CapabilityGrants[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for InitialState

	if all {
		switch v := interface{}(m.GetWorkflowContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SpawnAgentRequestValidationError{
					field:  "WorkflowContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SpawnAgentRequestValidationError{
					field:  "WorkflowContext",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetWorkflowContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SpawnAgentRequestValidationError{
				field:  "WorkflowContext",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SpawnAgentRequestMultiError(errors)
	}

	return nil
}

// SpawnAgentRequestMultiError is an error wrapping multiple validation errors
// returned by SpawnAgentRequest.ValidateAll() if the designated constraints
// aren't met.
type SpawnAgentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SpawnAgentRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SpawnAgentRequestMultiError) AllErrors() []error { return m }

// SpawnAgentRequestValidationError is the validation error returned by
// SpawnAgentRequest.Validate if the designated constraints aren't met.
type SpawnAgentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SpawnAgentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SpawnAgentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SpawnAgentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SpawnAgentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SpawnAgentRequestValidationError) ErrorName() string {
	return "SpawnAgentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SpawnAgentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpawnAgentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SpawnAgentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SpawnAgentRequestValidationError{}

// Validate checks the field values on AgentDefinition with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AgentDefinition) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AgentDefinition with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AgentDefinitionMultiError, or nil if none found.
func (m *AgentDefinition) ValidateAll() error {
	return m.validate(true)
}

func (m *AgentDefinition) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Version

	// no validation rules for Type

	// no validation rules for Config

	if len(errors) > 0 {
		return AgentDefinitionMultiError(errors)
	}

	return nil
}

// AgentDefinitionMultiError is an error wrapping multiple validation errors
// returned by AgentDefinition.ValidateAll() if the designated constraints
// aren't met.
type AgentDefinitionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AgentDefinitionMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AgentDefinitionMultiError) AllErrors() []error { return m }

// AgentDefinitionValidationError is the validation error returned by
// AgentDefinition.Validate if the designated constraints aren't met.
type AgentDefinitionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AgentDefinitionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AgentDefinitionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AgentDefinitionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AgentDefinitionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AgentDefinitionValidationError) ErrorName() string { return "AgentDefinitionValidationError" }

// Error satisfies the builtin error interface
func (e AgentDefinitionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAgentDefinition.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AgentDefinitionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AgentDefinitionValidationError{}

// Validate checks the field values on SpawnAgentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SpawnAgentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SpawnAgentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SpawnAgentResponseMultiError, or nil if none found.
func (m *SpawnAgentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SpawnAgentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AgentId

	// no validation rules for State

	// no validation rules for Error

	if len(errors) > 0 {
		return SpawnAgentResponseMultiError(errors)
	}

	return nil
}

// SpawnAgentResponseMultiError is an error wrapping multiple validation errors
// returned by SpawnAgentResponse.ValidateAll() if the designated constraints
// aren't met.
type SpawnAgentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SpawnAgentResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SpawnAgentResponseMultiError) AllErrors() []error { return m }

// SpawnAgentResponseValidationError is the validation error returned by
// SpawnAgentResponse.Validate if the designated constraints aren't met.
type SpawnAgentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SpawnAgentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SpawnAgentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SpawnAgentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SpawnAgentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SpawnAgentResponseValidationError) ErrorName() string {
	return "SpawnAgentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SpawnAgentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpawnAgentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SpawnAgentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SpawnAgentResponseValidationError{}

// Validate checks the field values on GetAgentStateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAgentStateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAgentStateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAgentStateRequestMultiError, or nil if none found.
func (m *GetAgentStateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAgentStateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AgentId

	if len(errors) > 0 {
		return GetAgentStateRequestMultiError(errors)
	}

	return nil
}

// GetAgentStateRequestMultiError is an error wrapping multiple validation
// errors returned by GetAgentStateRequest.ValidateAll() if the designated
// constraints aren't met.
type GetAgentStateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAgentStateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAgentStateRequestMultiError) AllErrors() []error { return m }

// GetAgentStateRequestValidationError is the validation error returned by
// GetAgentStateRequest.Validate if the designated constraints aren't met.
type GetAgentStateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAgentStateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAgentStateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAgentStateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAgentStateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAgentStateRequestValidationError) ErrorName() string {
	return "GetAgentStateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetAgentStateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAgentStateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAgentStateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAgentStateRequestValidationError{}

// Validate checks the field values on GetAgentStateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAgentStateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAgentStateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAgentStateResponseMultiError, or nil if none found.
func (m *GetAgentStateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAgentStateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetState()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetAgentStateResponseValidationError{
					field:  "State",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetAgentStateResponseValidationError{
					field:  "State",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetState()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetAgentStateResponseValidationError{
				field:  "State",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetAgentStateResponseMultiError(errors)
	}

	return nil
}

// GetAgentStateResponseMultiError is an error wrapping multiple validation
// errors returned by GetAgentStateResponse.ValidateAll() if the designated
// constraints aren't met.
type GetAgentStateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAgentStateResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAgentStateResponseMultiError) AllErrors() []error { return m }

// GetAgentStateResponseValidationError is the validation error returned by
// GetAgentStateResponse.Validate if the designated constraints aren't met.
type GetAgentStateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAgentStateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAgentStateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAgentStateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAgentStateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAgentStateResponseValidationError) ErrorName() string {
	return "GetAgentStateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetAgentStateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAgentStateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAgentStateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAgentStateResponseValidationError{}

// Validate checks the field values on AgentState with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AgentState) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AgentState with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AgentStateMultiError, or
// nil if none found.
func (m *AgentState) ValidateAll() error {
	return m.validate(true)
}

func (m *AgentState) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AgentId

	// no validation rules for State

	// no validation rules for CurrentStep

	// no validation rules for Variables

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return AgentStateMultiError(errors)
	}

	return nil
}

// AgentStateMultiError is an error wrapping multiple validation errors
// returned by AgentState.ValidateAll() if the designated constraints aren't met.
type AgentStateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AgentStateMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AgentStateMultiError) AllErrors() []error { return m }

// AgentStateValidationError is the validation error returned by
// AgentState.Validate if the designated constraints aren't met.
type AgentStateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AgentStateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AgentStateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AgentStateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AgentStateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AgentStateValidationError) ErrorName() string { return "AgentStateValidationError" }

// Error satisfies the builtin error interface
func (e AgentStateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAgentState.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AgentStateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AgentStateValidationError{}

// Validate checks the field values on ExecuteStepRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ExecuteStepRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExecuteStepRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExecuteStepRequestMultiError, or nil if none found.
func (m *ExecuteStepRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ExecuteStepRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AgentId

	// no validation rules for StepName

	// no validation rules for Tool

	// no validation rules for Input

	if all {
		switch v := interface{}(m.GetCapabilityGrant()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ExecuteStepRequestValidationError{
					field:  "CapabilityGrant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ExecuteStepRequestValidationError{
					field:  "CapabilityGrant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCapabilityGrant()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ExecuteStepRequestValidationError{
				field:  "CapabilityGrant",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ExecuteStepRequestMultiError(errors)
	}

	return nil
}

// ExecuteStepRequestMultiError is an error wrapping multiple validation errors
// returned by ExecuteStepRequest.ValidateAll() if the designated constraints
// aren't met.
type ExecuteStepRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExecuteStepRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExecuteStepRequestMultiError) AllErrors() []error { return m }

// ExecuteStepRequestValidationError is the validation error returned by
// ExecuteStepRequest.Validate if the designated constraints aren't met.
type ExecuteStepRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExecuteStepRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExecuteStepRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExecuteStepRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExecuteStepRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExecuteStepRequestValidationError) ErrorName() string {
	return "ExecuteStepRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ExecuteStepRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExecuteStepRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExecuteStepRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExecuteStepRequestValidationError{}

// Validate checks the field values on ExecuteStepResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ExecuteStepResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExecuteStepResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExecuteStepResponseMultiError, or nil if none found.
func (m *ExecuteStepResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ExecuteStepResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Output

	// no validation rules for ErrorCode

	// no validation rules for ErrorMessage

	// no validation rules for DurationMs

	if all {
		switch v := interface{}(m.GetCheckpoint()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ExecuteStepResponseValidationError{
					field:  "Checkpoint",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ExecuteStepResponseValidationError{
					field:  "Checkpoint",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCheckpoint()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ExecuteStepResponseValidationError{
				field:  "Checkpoint",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetResources()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ExecuteStepResponseValidationError{
					field:  "Resources",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ExecuteStepResponseValidationError{
					field:  "Resources",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResources()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ExecuteStepResponseValidationError{
				field:  "Resources",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ExecuteStepResponseMultiError(errors)
	}

	return nil
}

// ExecuteStepResponseMultiError is an error wrapping multiple validation
// errors returned by ExecuteStepResponse.ValidateAll() if the designated
// constraints aren't met.
type ExecuteStepResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExecuteStepResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExecuteStepResponseMultiError) AllErrors() []error { return m }

// ExecuteStepResponseValidationError is the validation error returned by
// ExecuteStepResponse.Validate if the designated constraints aren't met.
type ExecuteStepResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExecuteStepResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExecuteStepResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExecuteStepResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExecuteStepResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExecuteStepResponseValidationError) ErrorName() string {
	return "ExecuteStepResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ExecuteStepResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExecuteStepResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExecuteStepResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExecuteStepResponseValidationError{}

// Validate checks the field values on CheckpointRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CheckpointRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckpointRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckpointRequestMultiError, or nil if none found.
func (m *CheckpointRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckpointRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AgentId

	// no validation rules for ExecutionId

	// no validation rules for State

	if len(errors) > 0 {
		return CheckpointRequestMultiError(errors)
	}

	return nil
}

// CheckpointRequestMultiError is an error wrapping multiple validation errors
// returned by CheckpointRequest.ValidateAll() if the designated constraints
// aren't met.
type CheckpointRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckpointRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckpointRequestMultiError) AllErrors() []error { return m }

// CheckpointRequestValidationError is the validation error returned by
// CheckpointRequest.Validate if the designated constraints aren't met.
type CheckpointRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckpointRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckpointRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckpointRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckpointRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckpointRequestValidationError) ErrorName() string {
	return "CheckpointRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CheckpointRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckpointRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckpointRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckpointRequestValidationError{}

// Validate checks the field values on CheckpointResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckpointResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckpointResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckpointResponseMultiError, or nil if none found.
func (m *CheckpointResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckpointResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CheckpointId

	// no validation rules for CreatedAt

	// no validation rules for SizeBytes

	if len(errors) > 0 {
		return CheckpointResponseMultiError(errors)
	}

	return nil
}

// CheckpointResponseMultiError is an error wrapping multiple validation errors
// returned by CheckpointResponse.ValidateAll() if the designated constraints
// aren't met.
type CheckpointResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckpointResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckpointResponseMultiError) AllErrors() []error { return m }

// CheckpointResponseValidationError is the validation error returned by
// CheckpointResponse.Validate if the designated constraints aren't met.
type CheckpointResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckpointResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckpointResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckpointResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckpointResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckpointResponseValidationError) ErrorName() string {
	return "CheckpointResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CheckpointResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckpointResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckpointResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckpointResponseValidationError{}

// Validate checks the field values on RestoreRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RestoreRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RestoreRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RestoreRequestMultiError,
// or nil if none found.
func (m *RestoreRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RestoreRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CheckpointId

	if len(errors) > 0 {
		return RestoreRequestMultiError(errors)
	}

	return nil
}

// RestoreRequestMultiError is an error wrapping multiple validation errors
// returned by RestoreRequest.ValidateAll() if the designated constraints
// aren't met.
type RestoreRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RestoreRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RestoreRequestMultiError) AllErrors() []error { return m }

// RestoreRequestValidationError is the validation error returned by
// RestoreRequest.Validate if the designated constraints aren't met.
type RestoreRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RestoreRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RestoreRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RestoreRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RestoreRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RestoreRequestValidationError) ErrorName() string { return "RestoreRequestValidationError" }

// Error satisfies the builtin error interface
func (e RestoreRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRestoreRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RestoreRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RestoreRequestValidationError{}

// Validate checks the field values on RestoreResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RestoreResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RestoreResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RestoreResponseMultiError, or nil if none found.
func (m *RestoreResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RestoreResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for State

	// no validation rules for RestoredAt

	if len(errors) > 0 {
		return RestoreResponseMultiError(errors)
	}

	return nil
}

// RestoreResponseMultiError is an error wrapping multiple validation errors
// returned by RestoreResponse.ValidateAll() if the designated constraints
// aren't met.
type RestoreResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RestoreResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RestoreResponseMultiError) AllErrors() []error { return m }

// RestoreResponseValidationError is the validation error returned by
// RestoreResponse.Validate if the designated constraints aren't met.
type RestoreResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RestoreResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RestoreResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RestoreResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RestoreResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RestoreResponseValidationError) ErrorName() string { return "RestoreResponseValidationError" }

// Error satisfies the builtin error interface
func (e RestoreResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRestoreResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RestoreResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RestoreResponseValidationError{}

// Validate checks the field values on TerminateAgentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TerminateAgentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TerminateAgentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TerminateAgentRequestMultiError, or nil if none found.
func (m *TerminateAgentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TerminateAgentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AgentId

	// no validation rules for Reason

	if len(errors) > 0 {
		return TerminateAgentRequestMultiError(errors)
	}

	return nil
}

// TerminateAgentRequestMultiError is an error wrapping multiple validation
// errors returned by TerminateAgentRequest.ValidateAll() if the designated
// constraints aren't met.
type TerminateAgentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TerminateAgentRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TerminateAgentRequestMultiError) AllErrors() []error { return m }

// TerminateAgentRequestValidationError is the validation error returned by
// TerminateAgentRequest.Validate if the designated constraints aren't met.
type TerminateAgentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TerminateAgentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TerminateAgentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TerminateAgentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TerminateAgentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TerminateAgentRequestValidationError) ErrorName() string {
	return "TerminateAgentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TerminateAgentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTerminateAgentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TerminateAgentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TerminateAgentRequestValidationError{}

// Validate checks the field values on TerminateAgentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TerminateAgentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TerminateAgentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TerminateAgentResponseMultiError, or nil if none found.
func (m *TerminateAgentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TerminateAgentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	if len(errors) > 0 {
		return TerminateAgentResponseMultiError(errors)
	}

	return nil
}

// TerminateAgentResponseMultiError is an error wrapping multiple validation
// errors returned by TerminateAgentResponse.ValidateAll() if the designated
// constraints aren't met.
type TerminateAgentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TerminateAgentResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TerminateAgentResponseMultiError) AllErrors() []error { return m }

// TerminateAgentResponseValidationError is the validation error returned by
// TerminateAgentResponse.Validate if the designated constraints aren't met.
type TerminateAgentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TerminateAgentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TerminateAgentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TerminateAgentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TerminateAgentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TerminateAgentResponseValidationError) ErrorName() string {
	return "TerminateAgentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e TerminateAgentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTerminateAgentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TerminateAgentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TerminateAgentResponseValidationError{}

// Validate checks the field values on Checkpoint with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Checkpoint) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Checkpoint with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CheckpointMultiError, or
// nil if none found.
func (m *Checkpoint) ValidateAll() error {
	return m.validate(true)
}

func (m *Checkpoint) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CheckpointId

	// no validation rules for AgentId

	// no validation rules for ExecutionId

	// no validation rules for State

	// no validation rules for CreatedAt

	// no validation rules for SizeBytes

	if len(errors) > 0 {
		return CheckpointMultiError(errors)
	}

	return nil
}

// CheckpointMultiError is an error wrapping multiple validation errors
// returned by Checkpoint.ValidateAll() if the designated constraints aren't met.
type CheckpointMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckpointMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckpointMultiError) AllErrors() []error { return m }

// CheckpointValidationError is the validation error returned by
// Checkpoint.Validate if the designated constraints aren't met.
type CheckpointValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckpointValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckpointValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckpointValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckpointValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckpointValidationError) ErrorName() string { return "CheckpointValidationError" }

// Error satisfies the builtin error interface
func (e CheckpointValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckpoint.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckpointValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckpointValidationError{}

// Validate checks the field values on HealthLiveRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *HealthLiveRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthLiveRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthLiveRequestMultiError, or nil if none found.
func (m *HealthLiveRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthLiveRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return HealthLiveRequestMultiError(errors)
	}

	return nil
}

// HealthLiveRequestMultiError is an error wrapping multiple validation errors
// returned by HealthLiveRequest.ValidateAll() if the designated constraints
// aren't met.
type HealthLiveRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthLiveRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthLiveRequestMultiError) AllErrors() []error { return m }

// HealthLiveRequestValidationError is the validation error returned by
// HealthLiveRequest.Validate if the designated constraints aren't met.
type HealthLiveRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthLiveRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthLiveRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthLiveRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthLiveRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthLiveRequestValidationError) ErrorName() string {
	return "HealthLiveRequestValidationError"
}

// Error satisfies the builtin error interface
func (e HealthLiveRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthLiveRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthLiveRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthLiveRequestValidationError{}

// Validate checks the field values on HealthLiveResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HealthLiveResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthLiveResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthLiveResponseMultiError, or nil if none found.
func (m *HealthLiveResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthLiveResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return HealthLiveResponseMultiError(errors)
	}

	return nil
}

// HealthLiveResponseMultiError is an error wrapping multiple validation errors
// returned by HealthLiveResponse.ValidateAll() if the designated constraints
// aren't met.
type HealthLiveResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthLiveResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthLiveResponseMultiError) AllErrors() []error { return m }

// HealthLiveResponseValidationError is the validation error returned by
// HealthLiveResponse.Validate if the designated constraints aren't met.
type HealthLiveResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthLiveResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthLiveResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthLiveResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthLiveResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthLiveResponseValidationError) ErrorName() string {
	return "HealthLiveResponseValidationError"
}

// Error satisfies the builtin error interface
func (e HealthLiveResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthLiveResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthLiveResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthLiveResponseValidationError{}

// Validate checks the field values on HealthReadyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HealthReadyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthReadyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthReadyRequestMultiError, or nil if none found.
func (m *HealthReadyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthReadyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return HealthReadyRequestMultiError(errors)
	}

	return nil
}

// HealthReadyRequestMultiError is an error wrapping multiple validation errors
// returned by HealthReadyRequest.ValidateAll() if the designated constraints
// aren't met.
type HealthReadyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthReadyRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthReadyRequestMultiError) AllErrors() []error { return m }

// HealthReadyRequestValidationError is the validation error returned by
// HealthReadyRequest.Validate if the designated constraints aren't met.
type HealthReadyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthReadyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthReadyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthReadyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthReadyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthReadyRequestValidationError) ErrorName() string {
	return "HealthReadyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e HealthReadyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthReadyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthReadyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthReadyRequestValidationError{}

// Validate checks the field values on HealthReadyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HealthReadyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthReadyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthReadyResponseMultiError, or nil if none found.
func (m *HealthReadyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthReadyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	for idx, item := range m.GetChecks() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HealthReadyResponseValidationError{
						field:  fmt.Sprintf("Checks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HealthReadyResponseValidationError{
						field:  fmt.Sprintf("Checks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HealthReadyResponseValidationError{
					field:  fmt.Sprintf("Checks[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return HealthReadyResponseMultiError(errors)
	}

	return nil
}

// HealthReadyResponseMultiError is an error wrapping multiple validation
// errors returned by HealthReadyResponse.ValidateAll() if the designated
// constraints aren't met.
type HealthReadyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthReadyResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthReadyResponseMultiError) AllErrors() []error { return m }

// HealthReadyResponseValidationError is the validation error returned by
// HealthReadyResponse.Validate if the designated constraints aren't met.
type HealthReadyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthReadyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthReadyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthReadyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthReadyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthReadyResponseValidationError) ErrorName() string {
	return "HealthReadyResponseValidationError"
}

// Error satisfies the builtin error interface
func (e HealthReadyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthReadyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthReadyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthReadyResponseValidationError{}
