// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: api/proto/gix/harness/v1/harness.proto

package harnessv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HarnessService_SpawnAgent_FullMethodName     = "/gix.harness.v1.HarnessService/SpawnAgent"
	HarnessService_GetAgentState_FullMethodName  = "/gix.harness.v1.HarnessService/GetAgentState"
	HarnessService_ExecuteStep_FullMethodName    = "/gix.harness.v1.HarnessService/ExecuteStep"
	HarnessService_Checkpoint_FullMethodName     = "/gix.harness.v1.HarnessService/Checkpoint"
	HarnessService_Restore_FullMethodName        = "/gix.harness.v1.HarnessService/Restore"
	HarnessService_TerminateAgent_FullMethodName = "/gix.harness.v1.HarnessService/TerminateAgent"
	HarnessService_HealthLive_FullMethodName     = "/gix.harness.v1.HarnessService/HealthLive"
	HarnessService_HealthReady_FullMethodName    = "/gix.harness.v1.HarnessService/HealthReady"
)

// HarnessServiceClient is the client API for HarnessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HarnessServiceClient interface {
	SpawnAgent(ctx context.Context, in *SpawnAgentRequest, opts ...grpc.CallOption) (*SpawnAgentResponse, error)
	GetAgentState(ctx context.Context, in *GetAgentStateRequest, opts ...grpc.CallOption) (*GetAgentStateResponse, error)
	ExecuteStep(ctx context.Context, in *ExecuteStepRequest, opts ...grpc.CallOption) (*ExecuteStepResponse, error)
	Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	TerminateAgent(ctx context.Context, in *TerminateAgentRequest, opts ...grpc.CallOption) (*TerminateAgentResponse, error)
	HealthLive(ctx context.Context, in *HealthLiveRequest, opts ...grpc.CallOption) (*HealthLiveResponse, error)
	HealthReady(ctx context.Context, in *HealthReadyRequest, opts ...grpc.CallOption) (*HealthReadyResponse, error)
}

type harnessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHarnessServiceClient(cc grpc.ClientConnInterface) HarnessServiceClient {
	return &harnessServiceClient{cc}
}

func (c *harnessServiceClient) SpawnAgent(ctx context.Context, in *SpawnAgentRequest, opts ...grpc.CallOption) (*SpawnAgentResponse, error) {
	out := new(SpawnAgentResponse)
	err := c.cc.Invoke(ctx, HarnessService_SpawnAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harnessServiceClient) GetAgentState(ctx context.Context, in *GetAgentStateRequest, opts ...grpc.CallOption) (*GetAgentStateResponse, error) {
	out := new(GetAgentStateResponse)
	err := c.cc.Invoke(ctx, HarnessService_GetAgentState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harnessServiceClient) ExecuteStep(ctx context.Context, in *ExecuteStepRequest, opts ...grpc.CallOption) (*ExecuteStepResponse, error) {
	out := new(ExecuteStepResponse)
	err := c.cc.Invoke(ctx, HarnessService_ExecuteStep_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harnessServiceClient) Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error) {
	out := new(CheckpointResponse)
	err := c.cc.Invoke(ctx, HarnessService_Checkpoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harnessServiceClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, HarnessService_Restore_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harnessServiceClient) TerminateAgent(ctx context.Context, in *TerminateAgentRequest, opts ...grpc.CallOption) (*TerminateAgentResponse, error) {
	out := new(TerminateAgentResponse)
	err := c.cc.Invoke(ctx, HarnessService_TerminateAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harnessServiceClient) HealthLive(ctx context.Context, in *HealthLiveRequest, opts ...grpc.CallOption) (*HealthLiveResponse, error) {
	out := new(HealthLiveResponse)
	err := c.cc.Invoke(ctx, HarnessService_HealthLive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harnessServiceClient) HealthReady(ctx context.Context, in *HealthReadyRequest, opts ...grpc.CallOption) (*HealthReadyResponse, error) {
	out := new(HealthReadyResponse)
	err := c.cc.Invoke(ctx, HarnessService_HealthReady_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HarnessServiceServer is the server API for HarnessService service.
// All implementations must embed UnimplementedHarnessServiceServer
// for forward compatibility
type HarnessServiceServer interface {
	SpawnAgent(context.Context, *SpawnAgentRequest) (*SpawnAgentResponse, error)
	GetAgentState(context.Context, *GetAgentStateRequest) (*GetAgentStateResponse, error)
	ExecuteStep(context.Context, *ExecuteStepRequest) (*ExecuteStepResponse, error)
	Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error)
	Restore(context.Context, *RestoreRequest) (*RestoreResponse, error)
	TerminateAgent(context.Context, *TerminateAgentRequest) (*TerminateAgentResponse, error)
	HealthLive(context.Context, *HealthLiveRequest) (*HealthLiveResponse, error)
	HealthReady(context.Context, *HealthReadyRequest) (*HealthReadyResponse, error)
	mustEmbedUnimplementedHarnessServiceServer()
}

// UnimplementedHarnessServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHarnessServiceServer struct {
}

func (UnimplementedHarnessServiceServer) SpawnAgent(context.Context, *SpawnAgentRequest) (*SpawnAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpawnAgent not implemented")
}
func (UnimplementedHarnessServiceServer) GetAgentState(context.Context, *GetAgentStateRequest) (*GetAgentStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentState not implemented")
}
func (UnimplementedHarnessServiceServer) ExecuteStep(context.Context, *ExecuteStepRequest) (*ExecuteStepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteStep not implemented")
}
func (UnimplementedHarnessServiceServer) Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedHarnessServiceServer) Restore(context.Context, *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedHarnessServiceServer) TerminateAgent(context.Context, *TerminateAgentRequest) (*TerminateAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminateAgent not implemented")
}
func (UnimplementedHarnessServiceServer) HealthLive(context.Context, *HealthLiveRequest) (*HealthLiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthLive not implemented")
}
func (UnimplementedHarnessServiceServer) HealthReady(context.Context, *HealthReadyRequest) (*HealthReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthReady not implemented")
}
func (UnimplementedHarnessServiceServer) mustEmbedUnimplementedHarnessServiceServer() {}

// UnsafeHarnessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HarnessServiceServer will
// result in compilation errors.
type UnsafeHarnessServiceServer interface {
	mustEmbedUnimplementedHarnessServiceServer()
}

func RegisterHarnessServiceServer(s grpc.ServiceRegistrar, srv HarnessServiceServer) {
	s.RegisterService(&HarnessService_ServiceDesc, srv)
}

func _HarnessService_SpawnAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarnessServiceServer).SpawnAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HarnessService_SpawnAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarnessServiceServer).SpawnAgent(ctx, req.(*SpawnAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarnessService_GetAgentState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarnessServiceServer).GetAgentState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HarnessService_GetAgentState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarnessServiceServer).GetAgentState(ctx, req.(*GetAgentStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarnessService_ExecuteStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarnessServiceServer).ExecuteStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HarnessService_ExecuteStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarnessServiceServer).ExecuteStep(ctx, req.(*ExecuteStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarnessService_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarnessServiceServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HarnessService_Checkpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarnessServiceServer).Checkpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarnessService_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarnessServiceServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HarnessService_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarnessServiceServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarnessService_TerminateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarnessServiceServer).TerminateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HarnessService_TerminateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarnessServiceServer).TerminateAgent(ctx, req.(*TerminateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarnessService_HealthLive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthLiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarnessServiceServer).HealthLive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HarnessService_HealthLive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarnessServiceServer).HealthLive(ctx, req.(*HealthLiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarnessService_HealthReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarnessServiceServer).HealthReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HarnessService_HealthReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarnessServiceServer).HealthReady(ctx, req.(*HealthReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HarnessService_ServiceDesc is the grpc.ServiceDesc for HarnessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HarnessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gix.harness.v1.HarnessService",
	HandlerType: (*HarnessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SpawnAgent",
			Handler:    _HarnessService_SpawnAgent_Handler,
		},
		{
			MethodName: "GetAgentState",
			Handler:    _HarnessService_GetAgentState_Handler,
		},
		{
			MethodName: "ExecuteStep",
			Handler:    _HarnessService_ExecuteStep_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _HarnessService_Checkpoint_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _HarnessService_Restore_Handler,
		},
		{
			MethodName: "TerminateAgent",
			Handler:    _HarnessService_TerminateAgent_Handler,
		},
		{
			MethodName: "HealthLive",
			Handler:    _HarnessService_HealthLive_Handler,
		},
		{
			MethodName: "HealthReady",
			Handler:    _HarnessService_HealthReady_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/gix/harness/v1/harness.proto",
}
