// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/proto/gix/gateway/v1/gateway.proto

package gatewayv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ExecuteWorkflowRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ExecuteWorkflowRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExecuteWorkflowRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExecuteWorkflowRequestMultiError, or nil if none found.
func (m *ExecuteWorkflowRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ExecuteWorkflowRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for WorkflowId

	if all {
		switch v := interface{}(m.GetWorkflow()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ExecuteWorkflowRequestValidationError{
					field:  "Workflow",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ExecuteWorkflowRequestValidationError{
					field:  "Workflow",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetWorkflow()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ExecuteWorkflowRequestValidationError{
				field:  "Workflow",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Input

	for idx, item := range m.GetCapabilities() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ExecuteWorkflowRequestValidationError{
						field:  fmt.Sprintf("Capabilities[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ExecuteWorkflowRequestValidationError{
						field:  fmt.Sprintf("Capabilities[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ExecuteWorkflowRequestValidationError{
					field:  fmt.Sprintf("Capabilities[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for IdempotencyKey

	if len(errors) > 0 {
		return ExecuteWorkflowRequestMultiError(errors)
	}

	return nil
}

// ExecuteWorkflowRequestMultiError is an error wrapping multiple validation
// errors returned by ExecuteWorkflowRequest.ValidateAll() if the designated
// constraints aren't met.
type ExecuteWorkflowRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExecuteWorkflowRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExecuteWorkflowRequestMultiError) AllErrors() []error { return m }

// ExecuteWorkflowRequestValidationError is the validation error returned by
// ExecuteWorkflowRequest.Validate if the designated constraints aren't met.
type ExecuteWorkflowRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExecuteWorkflowRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExecuteWorkflowRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExecuteWorkflowRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExecuteWorkflowRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExecuteWorkflowRequestValidationError) ErrorName() string {
	return "ExecuteWorkflowRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ExecuteWorkflowRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExecuteWorkflowRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExecuteWorkflowRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExecuteWorkflowRequestValidationError{}

// Validate checks the field values on ExecuteWorkflowResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ExecuteWorkflowResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExecuteWorkflowResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExecuteWorkflowResponseMultiError, or nil if none found.
func (m *ExecuteWorkflowResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ExecuteWorkflowResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ExecutionId

	// no validation rules for Status

	// no validation rules for ErrorCode

	// no validation rules for ErrorMessage

	// no validation rules for Result

	if len(errors) > 0 {
		return ExecuteWorkflowResponseMultiError(errors)
	}

	return nil
}

// ExecuteWorkflowResponseMultiError is an error wrapping multiple validation
// errors returned by ExecuteWorkflowResponse.ValidateAll() if the designated
// constraints aren't met.
type ExecuteWorkflowResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExecuteWorkflowResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExecuteWorkflowResponseMultiError) AllErrors() []error { return m }

// ExecuteWorkflowResponseValidationError is the validation error returned by
// ExecuteWorkflowResponse.Validate if the designated constraints aren't met.
type ExecuteWorkflowResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExecuteWorkflowResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExecuteWorkflowResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExecuteWorkflowResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExecuteWorkflowResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExecuteWorkflowResponseValidationError) ErrorName() string {
	return "ExecuteWorkflowResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ExecuteWorkflowResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExecuteWorkflowResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExecuteWorkflowResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExecuteWorkflowResponseValidationError{}

// Validate checks the field values on GetExecutionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetExecutionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetExecutionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetExecutionRequestMultiError, or nil if none found.
func (m *GetExecutionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetExecutionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ExecutionId

	if len(errors) > 0 {
		return GetExecutionRequestMultiError(errors)
	}

	return nil
}

// GetExecutionRequestMultiError is an error wrapping multiple validation
// errors returned by GetExecutionRequest.ValidateAll() if the designated
// constraints aren't met.
type GetExecutionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetExecutionRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetExecutionRequestMultiError) AllErrors() []error { return m }

// GetExecutionRequestValidationError is the validation error returned by
// GetExecutionRequest.Validate if the designated constraints aren't met.
type GetExecutionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetExecutionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetExecutionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetExecutionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetExecutionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetExecutionRequestValidationError) ErrorName() string {
	return "GetExecutionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetExecutionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetExecutionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetExecutionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetExecutionRequestValidationError{}

// Validate checks the field values on GetExecutionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetExecutionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetExecutionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetExecutionResponseMultiError, or nil if none found.
func (m *GetExecutionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetExecutionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetExecution()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetExecutionResponseValidationError{
					field:  "Execution",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetExecutionResponseValidationError{
					field:  "Execution",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExecution()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetExecutionResponseValidationError{
				field:  "Execution",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetExecutionResponseMultiError(errors)
	}

	return nil
}

// GetExecutionResponseMultiError is an error wrapping multiple validation
// errors returned by GetExecutionResponse.ValidateAll() if the designated
// constraints aren't met.
type GetExecutionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetExecutionResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetExecutionResponseMultiError) AllErrors() []error { return m }

// GetExecutionResponseValidationError is the validation error returned by
// GetExecutionResponse.Validate if the designated constraints aren't met.
type GetExecutionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetExecutionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetExecutionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetExecutionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetExecutionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetExecutionResponseValidationError) ErrorName() string {
	return "GetExecutionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetExecutionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetExecutionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetExecutionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetExecutionResponseValidationError{}

// Validate checks the field values on CancelExecutionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CancelExecutionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CancelExecutionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CancelExecutionRequestMultiError, or nil if none found.
func (m *CancelExecutionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CancelExecutionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ExecutionId

	if len(errors) > 0 {
		return CancelExecutionRequestMultiError(errors)
	}

	return nil
}

// CancelExecutionRequestMultiError is an error wrapping multiple validation
// errors returned by CancelExecutionRequest.ValidateAll() if the designated
// constraints aren't met.
type CancelExecutionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CancelExecutionRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CancelExecutionRequestMultiError) AllErrors() []error { return m }

// CancelExecutionRequestValidationError is the validation error returned by
// CancelExecutionRequest.Validate if the designated constraints aren't met.
type CancelExecutionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CancelExecutionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CancelExecutionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CancelExecutionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CancelExecutionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CancelExecutionRequestValidationError) ErrorName() string {
	return "CancelExecutionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CancelExecutionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCancelExecutionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CancelExecutionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CancelExecutionRequestValidationError{}

// Validate checks the field values on CancelExecutionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CancelExecutionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CancelExecutionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CancelExecutionResponseMultiError, or nil if none found.
func (m *CancelExecutionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CancelExecutionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	if len(errors) > 0 {
		return CancelExecutionResponseMultiError(errors)
	}

	return nil
}

// CancelExecutionResponseMultiError is an error wrapping multiple validation
// errors returned by CancelExecutionResponse.ValidateAll() if the designated
// constraints aren't met.
type CancelExecutionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CancelExecutionResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CancelExecutionResponseMultiError) AllErrors() []error { return m }

// CancelExecutionResponseValidationError is the validation error returned by
// CancelExecutionResponse.Validate if the designated constraints aren't met.
type CancelExecutionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CancelExecutionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CancelExecutionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CancelExecutionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CancelExecutionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CancelExecutionResponseValidationError) ErrorName() string {
	return "CancelExecutionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CancelExecutionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCancelExecutionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CancelExecutionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CancelExecutionResponseValidationError{}

// Validate checks the field values on ExecutionRecord with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ExecutionRecord) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExecutionRecord with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExecutionRecordMultiError, or nil if none found.
func (m *ExecutionRecord) ValidateAll() error {
	return m.validate(true)
}

func (m *ExecutionRecord) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ExecutionId

	// no validation rules for WorkflowId

	// no validation rules for WorkflowType

	// no validation rules for Status

	// no validation rules for Input

	// no validation rules for Output

	// no validation rules for ErrorCode

	// no validation rules for ErrorMessage

	// no validation rules for StartedAt

	// no validation rules for CompletedAt

	// no validation rules for CorrelationId

	// no validation rules for TenantId

	if len(errors) > 0 {
		return ExecutionRecordMultiError(errors)
	}

	return nil
}

// ExecutionRecordMultiError is an error wrapping multiple validation errors
// returned by ExecutionRecord.ValidateAll() if the designated constraints
// aren't met.
type ExecutionRecordMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExecutionRecordMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExecutionRecordMultiError) AllErrors() []error { return m }

// ExecutionRecordValidationError is the validation error returned by
// ExecutionRecord.Validate if the designated constraints aren't met.
type ExecutionRecordValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExecutionRecordValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExecutionRecordValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExecutionRecordValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExecutionRecordValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExecutionRecordValidationError) ErrorName() string { return "ExecutionRecordValidationError" }

// Error satisfies the builtin error interface
func (e ExecutionRecordValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExecutionRecord.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExecutionRecordValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExecutionRecordValidationError{}

// Validate checks the field values on HealthLiveRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *HealthLiveRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthLiveRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthLiveRequestMultiError, or nil if none found.
func (m *HealthLiveRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthLiveRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return HealthLiveRequestMultiError(errors)
	}

	return nil
}

// HealthLiveRequestMultiError is an error wrapping multiple validation errors
// returned by HealthLiveRequest.ValidateAll() if the designated constraints
// aren't met.
type HealthLiveRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthLiveRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthLiveRequestMultiError) AllErrors() []error { return m }

// HealthLiveRequestValidationError is the validation error returned by
// HealthLiveRequest.Validate if the designated constraints aren't met.
type HealthLiveRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthLiveRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthLiveRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthLiveRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthLiveRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthLiveRequestValidationError) ErrorName() string {
	return "HealthLiveRequestValidationError"
}

// Error satisfies the builtin error interface
func (e HealthLiveRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthLiveRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthLiveRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthLiveRequestValidationError{}

// Validate checks the field values on HealthLiveResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HealthLiveResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthLiveResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthLiveResponseMultiError, or nil if none found.
func (m *HealthLiveResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthLiveResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return HealthLiveResponseMultiError(errors)
	}

	return nil
}

// HealthLiveResponseMultiError is an error wrapping multiple validation errors
// returned by HealthLiveResponse.ValidateAll() if the designated constraints
// aren't met.
type HealthLiveResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthLiveResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthLiveResponseMultiError) AllErrors() []error { return m }

// HealthLiveResponseValidationError is the validation error returned by
// HealthLiveResponse.Validate if the designated constraints aren't met.
type HealthLiveResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthLiveResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthLiveResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthLiveResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthLiveResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthLiveResponseValidationError) ErrorName() string {
	return "HealthLiveResponseValidationError"
}

// Error satisfies the builtin error interface
func (e HealthLiveResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthLiveResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthLiveResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthLiveResponseValidationError{}

// Validate checks the field values on HealthReadyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HealthReadyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthReadyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthReadyRequestMultiError, or nil if none found.
func (m *HealthReadyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthReadyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return HealthReadyRequestMultiError(errors)
	}

	return nil
}

// HealthReadyRequestMultiError is an error wrapping multiple validation errors
// returned by HealthReadyRequest.ValidateAll() if the designated constraints
// aren't met.
type HealthReadyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthReadyRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthReadyRequestMultiError) AllErrors() []error { return m }

// HealthReadyRequestValidationError is the validation error returned by
// HealthReadyRequest.Validate if the designated constraints aren't met.
type HealthReadyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthReadyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthReadyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthReadyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthReadyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthReadyRequestValidationError) ErrorName() string {
	return "HealthReadyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e HealthReadyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthReadyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthReadyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthReadyRequestValidationError{}

// Validate checks the field values on HealthReadyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HealthReadyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthReadyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthReadyResponseMultiError, or nil if none found.
func (m *HealthReadyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthReadyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	for idx, item := range m.GetChecks() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HealthReadyResponseValidationError{
						field:  fmt.Sprintf("Checks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HealthReadyResponseValidationError{
						field:  fmt.Sprintf("Checks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HealthReadyResponseValidationError{
					field:  fmt.Sprintf("Checks[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return HealthReadyResponseMultiError(errors)
	}

	return nil
}

// HealthReadyResponseMultiError is an error wrapping multiple validation
// errors returned by HealthReadyResponse.ValidateAll() if the designated
// constraints aren't met.
type HealthReadyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthReadyResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthReadyResponseMultiError) AllErrors() []error { return m }

// HealthReadyResponseValidationError is the validation error returned by
// HealthReadyResponse.Validate if the designated constraints aren't met.
type HealthReadyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthReadyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthReadyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthReadyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthReadyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthReadyResponseValidationError) ErrorName() string {
	return "HealthReadyResponseValidationError"
}

// Error satisfies the builtin error interface
func (e HealthReadyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthReadyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthReadyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthReadyResponseValidationError{}
