// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/proto/gix/policy/v1/policy.proto

package policyv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on EvaluateRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *EvaluateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EvaluateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EvaluateRequestMultiError, or nil if none found.
func (m *EvaluateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *EvaluateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetIdentity()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EvaluateRequestValidationError{
					field:  "Identity",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EvaluateRequestValidationError{
					field:  "Identity",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetIdentity()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EvaluateRequestValidationError{
				field:  "Identity",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Resource

	// no validation rules for Action

	// no validation rules for Context

	if len(errors) > 0 {
		return EvaluateRequestMultiError(errors)
	}

	return nil
}

// EvaluateRequestMultiError is an error wrapping multiple validation errors
// returned by EvaluateRequest.ValidateAll() if the designated constraints
// aren't met.
type EvaluateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EvaluateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EvaluateRequestMultiError) AllErrors() []error { return m }

// EvaluateRequestValidationError is the validation error returned by
// EvaluateRequest.Validate if the designated constraints aren't met.
type EvaluateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EvaluateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EvaluateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EvaluateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EvaluateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EvaluateRequestValidationError) ErrorName() string { return "EvaluateRequestValidationError" }

// Error satisfies the builtin error interface
func (e EvaluateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEvaluateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EvaluateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EvaluateRequestValidationError{}

// Validate checks the field values on EvaluateResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *EvaluateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EvaluateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EvaluateResponseMultiError, or nil if none found.
func (m *EvaluateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *EvaluateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Decision

	for idx, item := range m.GetGrants() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, EvaluateResponseValidationError{
						field:  fmt.Sprintf("Grants[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, EvaluateResponseValidationError{
						field:  fmt.Sprintf("Grants[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return EvaluateResponseValidationError{
					field:  fmt.Sprintf("Grants[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Reason

	if len(errors) > 0 {
		return EvaluateResponseMultiError(errors)
	}

	return nil
}

// EvaluateResponseMultiError is an error wrapping multiple validation errors
// returned by EvaluateResponse.ValidateAll() if the designated constraints
// aren't met.
type EvaluateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EvaluateResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EvaluateResponseMultiError) AllErrors() []error { return m }

// EvaluateResponseValidationError is the validation error returned by
// EvaluateResponse.Validate if the designated constraints aren't met.
type EvaluateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EvaluateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EvaluateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EvaluateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EvaluateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EvaluateResponseValidationError) ErrorName() string { return "EvaluateResponseValidationError" }

// Error satisfies the builtin error interface
func (e EvaluateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEvaluateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EvaluateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EvaluateResponseValidationError{}

// Validate checks the field values on GetCapabilitiesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCapabilitiesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCapabilitiesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCapabilitiesRequestMultiError, or nil if none found.
func (m *GetCapabilitiesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCapabilitiesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for WorkflowId

	// no validation rules for WorkflowType

	if len(errors) > 0 {
		return GetCapabilitiesRequestMultiError(errors)
	}

	return nil
}

// GetCapabilitiesRequestMultiError is an error wrapping multiple validation
// errors returned by GetCapabilitiesRequest.ValidateAll() if the designated
// constraints aren't met.
type GetCapabilitiesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCapabilitiesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCapabilitiesRequestMultiError) AllErrors() []error { return m }

// GetCapabilitiesRequestValidationError is the validation error returned by
// GetCapabilitiesRequest.Validate if the designated constraints aren't met.
type GetCapabilitiesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCapabilitiesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCapabilitiesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCapabilitiesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCapabilitiesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCapabilitiesRequestValidationError) ErrorName() string {
	return "GetCapabilitiesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCapabilitiesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCapabilitiesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCapabilitiesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCapabilitiesRequestValidationError{}

// Validate checks the field values on GetCapabilitiesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCapabilitiesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCapabilitiesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCapabilitiesResponseMultiError, or nil if none found.
func (m *GetCapabilitiesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCapabilitiesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetGrants() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetCapabilitiesResponseValidationError{
						field:  fmt.Sprintf("Grants[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetCapabilitiesResponseValidationError{
						field:  fmt.Sprintf("Grants[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetCapabilitiesResponseValidationError{
					field:  fmt.Sprintf("Grants[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetCapabilitiesResponseMultiError(errors)
	}

	return nil
}

// GetCapabilitiesResponseMultiError is an error wrapping multiple validation
// errors returned by GetCapabilitiesResponse.ValidateAll() if the designated
// constraints aren't met.
type GetCapabilitiesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCapabilitiesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCapabilitiesResponseMultiError) AllErrors() []error { return m }

// GetCapabilitiesResponseValidationError is the validation error returned by
// GetCapabilitiesResponse.Validate if the designated constraints aren't met.
type GetCapabilitiesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCapabilitiesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCapabilitiesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCapabilitiesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCapabilitiesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCapabilitiesResponseValidationError) ErrorName() string {
	return "GetCapabilitiesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetCapabilitiesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCapabilitiesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCapabilitiesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCapabilitiesResponseValidationError{}

// Validate checks the field values on HealthLiveRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *HealthLiveRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthLiveRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthLiveRequestMultiError, or nil if none found.
func (m *HealthLiveRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthLiveRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return HealthLiveRequestMultiError(errors)
	}

	return nil
}

// HealthLiveRequestMultiError is an error wrapping multiple validation errors
// returned by HealthLiveRequest.ValidateAll() if the designated constraints
// aren't met.
type HealthLiveRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthLiveRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthLiveRequestMultiError) AllErrors() []error { return m }

// HealthLiveRequestValidationError is the validation error returned by
// HealthLiveRequest.Validate if the designated constraints aren't met.
type HealthLiveRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthLiveRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthLiveRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthLiveRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthLiveRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthLiveRequestValidationError) ErrorName() string {
	return "HealthLiveRequestValidationError"
}

// Error satisfies the builtin error interface
func (e HealthLiveRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthLiveRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthLiveRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthLiveRequestValidationError{}

// Validate checks the field values on HealthLiveResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HealthLiveResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthLiveResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthLiveResponseMultiError, or nil if none found.
func (m *HealthLiveResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthLiveResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return HealthLiveResponseMultiError(errors)
	}

	return nil
}

// HealthLiveResponseMultiError is an error wrapping multiple validation errors
// returned by HealthLiveResponse.ValidateAll() if the designated constraints
// aren't met.
type HealthLiveResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthLiveResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthLiveResponseMultiError) AllErrors() []error { return m }

// HealthLiveResponseValidationError is the validation error returned by
// HealthLiveResponse.Validate if the designated constraints aren't met.
type HealthLiveResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthLiveResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthLiveResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthLiveResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthLiveResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthLiveResponseValidationError) ErrorName() string {
	return "HealthLiveResponseValidationError"
}

// Error satisfies the builtin error interface
func (e HealthLiveResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthLiveResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthLiveResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthLiveResponseValidationError{}

// Validate checks the field values on HealthReadyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HealthReadyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthReadyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthReadyRequestMultiError, or nil if none found.
func (m *HealthReadyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthReadyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return HealthReadyRequestMultiError(errors)
	}

	return nil
}

// HealthReadyRequestMultiError is an error wrapping multiple validation errors
// returned by HealthReadyRequest.ValidateAll() if the designated constraints
// aren't met.
type HealthReadyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthReadyRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthReadyRequestMultiError) AllErrors() []error { return m }

// HealthReadyRequestValidationError is the validation error returned by
// HealthReadyRequest.Validate if the designated constraints aren't met.
type HealthReadyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthReadyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthReadyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthReadyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthReadyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthReadyRequestValidationError) ErrorName() string {
	return "HealthReadyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e HealthReadyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthReadyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthReadyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthReadyRequestValidationError{}

// Validate checks the field values on HealthReadyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HealthReadyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthReadyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HealthReadyResponseMultiError, or nil if none found.
func (m *HealthReadyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthReadyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	for idx, item := range m.GetChecks() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HealthReadyResponseValidationError{
						field:  fmt.Sprintf("Checks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HealthReadyResponseValidationError{
						field:  fmt.Sprintf("Checks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HealthReadyResponseValidationError{
					field:  fmt.Sprintf("Checks[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return HealthReadyResponseMultiError(errors)
	}

	return nil
}

// HealthReadyResponseMultiError is an error wrapping multiple validation
// errors returned by HealthReadyResponse.ValidateAll() if the designated
// constraints aren't met.
type HealthReadyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthReadyResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthReadyResponseMultiError) AllErrors() []error { return m }

// HealthReadyResponseValidationError is the validation error returned by
// HealthReadyResponse.Validate if the designated constraints aren't met.
type HealthReadyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthReadyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthReadyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthReadyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthReadyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthReadyResponseValidationError) ErrorName() string {
	return "HealthReadyResponseValidationError"
}

// Error satisfies the builtin error interface
func (e HealthReadyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthReadyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthReadyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthReadyResponseValidationError{}
